# Auto-generated by tools/generate_struct.py -- do not edit by hand.

"""Field point / particle location, matching C `struct coordinate`."""
struct Coordinate{T}
    r::T
    theta::T
    phi::T
    t::T
end
Coordinate{T}(; r=zero(T), theta=zero(T), phi=zero(T), t=zero(T)) where {T} =
    Coordinate{T}(T(r), T(theta), T(phi), T(t))

"""Thread-safe effective-source context for circular Kerr orbits, generic over
the numeric type T (Float64, Float32, Float32sr, BigFloat, ...)."""
mutable struct EffsourceCtx{T}
    M::T
    a::T
    xp::Coordinate{T}
    A006::T
    A008::T
    A024::T
    A026::T
    A042::T
    A044::T
    A060::T
    A062::T
    A080::T
    A106::T
    A108::T
    A124::T
    A126::T
    A142::T
    A144::T
    A160::T
    A162::T
    A180::T
    A204::T
    A206::T
    A222::T
    A224::T
    A240::T
    A242::T
    A260::T
    A304::T
    A306::T
    A322::T
    A324::T
    A340::T
    A342::T
    A360::T
    A402::T
    A404::T
    A420::T
    A422::T
    A440::T
    A502::T
    A504::T
    A520::T
    A522::T
    A540::T
    A600::T
    A602::T
    A620::T
    A700::T
    A702::T
    A720::T
    A800::T
    A900::T
    alpha20::T
    alpha02::T
    beta::T

    EffsourceCtx{T}() where {T} = new{T}()
end

Base.eltype(::EffsourceCtx{T}) where {T} = T

"""Allocate a context for black-hole mass M and spin a."""
function effsource_create(M, a)
    T0 = promote_type(typeof(M), typeof(a))
    T = T0 <: Integer ? Float64 : T0   # float-ify integer inputs, keep SR types
    ctx = EffsourceCtx{T}()
    ctx.M = T(M)
    ctx.a = T(a)
    ctx.xp = Coordinate{T}()
    return ctx
end
