# ============================================================================
# Auto-generated by tools/generate_functions.py from kerr-circular-ctx.c.
# Do not edit by hand -- re-run the generator instead.
# ============================================================================

"""Real-space singular field PhiS at field point `x` (or `Offset`)."""
function phis(ctx::EffsourceCtx{T}, x::Coordinate{T}) where {T}
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
        r = x.r
        theta = x.theta
        phi = x.phi
        rp = xp.r
        thetap = xp.theta
        phip = xp.phi
        dr = r - rp
        dtheta = theta - thetap
        dphi = phi - phip
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr6 = dr3*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta8 = dtheta4*dtheta4
        sindphi = sin(T(0.5)*dphi)
        sindphi2 = sindphi*sindphi
        sindphi4 = sindphi2*sindphi2
        sindphi8 = sindphi4*sindphi4
        A = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + 
   (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + 
      (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2) + 
   (dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + 
      dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2))*sindphi2 + 
   (A008 + A108*dr)*sindphi8 + sindphi4*(dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + 
      (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4 + 
      (A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2)*sindphi2)
        alpha = alpha20*dr2 + alpha02*dtheta2
        rho2 = alpha + beta*sindphi2
        PhiS_out = A/((rho2)^(3) * sqrt(rho2))
    return PhiS_out
end

"""phis at an `Offset` from the particle (avoids the r-rp cancellation)."""
function phis(ctx::EffsourceCtx{T}, off::Offset{T}) where {T}
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
    rp = xp.r
    thetap = xp.theta
    dr = off.dr
    dtheta = off.dtheta
    dphi = off.dphi
    r = rp + dr
    theta = thetap + dtheta
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr6 = dr3*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta8 = dtheta4*dtheta4
        sindphi = sin(T(0.5)*dphi)
        sindphi2 = sindphi*sindphi
        sindphi4 = sindphi2*sindphi2
        sindphi8 = sindphi4*sindphi4
        A = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + 
   (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + 
      (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2) + 
   (dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + 
      dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2))*sindphi2 + 
   (A008 + A108*dr)*sindphi8 + sindphi4*(dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + 
      (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4 + 
      (A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2)*sindphi2)
        alpha = alpha20*dr2 + alpha02*dtheta2
        rho2 = alpha + beta*sindphi2
        PhiS_out = A/((rho2)^(3) * sqrt(rho2))
    return PhiS_out
end

"""Singular field, its first/second derivatives and the effective source.
Returns `(PhiS, dPhiS_dx[4], d2PhiS_dx2[10], src)` with component order
(t,r,theta,phi) and (tt,tr,ttheta,tphi,rr,rtheta,rphi,thetatheta,thetaphi,phiphi).
`comp=true` sums the source numerator with compensated (Neumaier) summation."""
calc(ctx::EffsourceCtx{T}, x::Coordinate{T}; comp::Bool=false) where {T} = _calc(ctx, x, Val(comp))
function _calc(ctx::EffsourceCtx{T}, x::Coordinate{T}, cm::Val) where {T}
    dPhiS_dx  = _ovec(T, 4)
    d2PhiS_dx2 = _ovec(T, 10)
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
        r = x.r
        theta = x.theta
        phi = x.phi
        rp = xp.r
        thetap = xp.theta
        phip = xp.phi
        dr = r - rp
        dtheta = theta - thetap
        dphi = phi - phip
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr5 = dr3*dr2
        dr6 = dr3*dr3
        dr7 = dr4*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta3 = dtheta2*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta5 = dtheta3*dtheta2
        dtheta6 = dtheta3*dtheta3
        dtheta7 = dtheta4*dtheta3
        dtheta8 = dtheta4*dtheta4
        R = sin(T(0.5)*dphi)
        R2 = R*R
        R3 = R2*R
        R4 = R2*R2
        R5 = R3*R2
        R6 = R3*R3
        R7 = R4*R3
        R8 = R4*R4
        dR = T(0.5)*cos(T(0.5)*dphi)
        om = M / (a*M + sqrt(M*((rp)^(3))))
        A = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2) + (dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2))*R2 + (A008 + A108*dr)*R8 + R4*(dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4 + (A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2)*R2)
        #= return =#
        dA_dr = 6*(A600 + A700*dr)*dr5 + A700*dr6 + 8*(A800 + A900*dr)*dr7 + A900*dr8 + 4*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dr3*dtheta2 + (A520 + 2*dr*(A620 + A720*dr) + A720*dr2)*dr4*dtheta2 + (2*dr*(A240 + A340*dr) + A340*dr2 + 4*(A440 + A540*dr)*dr3 + A540*dr4 + (A160 + 2*dr*(A260 + A360*dr) + A360*dr2)*dtheta2)*dtheta4 + A180*dtheta8 + (4*(A402 + A502*dr + (A602 + A702*dr)*dr2)*dr3 + (A502 + 2*dr*(A602 + A702*dr) + A702*dr2)*dr4 + (2*dr*(A222 + A322*dr) + A322*dr2 + 4*(A422 + A522*dr)*dr3 + A522*dr4)* dtheta2 + (A142 + 2*dr*(A242 + A342*dr) + A342*dr2 + A162*dtheta2)* dtheta4)*R2 + (2*dr*(A204 + A304*dr) + A304*dr2 + 4*(A404 + A504*dr)*dr3 + A504*dr4 + (A124 + 2*dr*(A224 + A324*dr) + A324*dr2)*dtheta2 + A144*dtheta4 + (A106 + 2*dr*(A206 + A306*dr) + A306*dr2 + A126*dtheta2)*R2)* R4 + A108*R8
        dA_dth = 2*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dr4*dtheta + 4*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta2)*dtheta3 + 2*(A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta5 + 8*(A080 + A180*dr)*dtheta7 + (2*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4)*dtheta + 4*(A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2)* dtheta3 + 2*(A062 + A162*dr)*dtheta5)*R2 + (2*(A024 + A124*dr + (A224 + A324*dr)*dr2)*dtheta + 4*(A044 + A144*dr)*dtheta3 + 2*(A026 + A126*dr)*dtheta*R2)* R4
        dA_dR = 2*((A402 + A502*dr + (A602 + A702*dr)*dr2)*dr4 + ((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4)*dtheta2 + (A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2)* dtheta4)*R + 4*((A204 + A304*dr)*dr2 + (A404 + A504*dr)*dr4 + (A024 + A124*dr + (A224 + A324*dr)*dr2)*dtheta2 + (A044 + A144*dr)*dtheta4 + (A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)* R2)*R3 + 2*(A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)*R5 + 8*(A008 + A108*dr)*R7
        dA_dph = dA_dR*dR
        dA_dt = -om*dA_dph
        d2A_dr2 = 30*(A600 + A700*dr)*dr4 + 12*A700*dr5 + 56*(A800 + A900*dr)*dr6 + 16*A900*dr7 + 12*dr2*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dtheta2 + 8*(A520 + 2*dr*(A620 + A720*dr) + A720*dr2)*dr3*dtheta2 + (4*A720*dr + 2*(A620 + A720*dr))*dr4*dtheta2 + (4*A340*dr + 2*(A240 + A340*dr) + 12*(A440 + A540*dr)*dr2 + 8*A540*dr3 + (4*A360*dr + 2*(A260 + A360*dr))*dtheta2)*dtheta4 + (12*dr2*(A402 + A502*dr + (A602 + A702*dr)*dr2) + 8*(A502 + 2*dr*(A602 + A702*dr) + A702*dr2)*dr3 + (4*A702*dr + 2*(A602 + A702*dr))*dr4 + (4*A322*dr + 2*(A222 + A322*dr) + 12*(A422 + A522*dr)*dr2 + 8*A522*dr3)*dtheta2 + (4*A342*dr + 2*(A242 + A342*dr))*dtheta4)* R2 + (4*A304*dr + 2*(A204 + A304*dr) + 12*(A404 + A504*dr)*dr2 + 8*A504*dr3 + (4*A324*dr + 2*(A224 + A324*dr))*dtheta2 + (4*A306*dr + 2*(A206 + A306*dr))*R2)*R4
        d2A_dth2 = 2*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dr4 + 12*dtheta2*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta2) + 18*(A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta4 + 56*(A080 + A180*dr)*dtheta6 + (2*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4) + 12*dtheta2*(A042 + A142*dr + (A242 + A342*dr)*dr2 +  (A062 + A162*dr)*dtheta2) + 18*(A062 + A162*dr)*dtheta4)*R2 + (2*(A024 + A124*dr + (A224 + A324*dr)*dr2) + 12*(A044 + A144*dr)*dtheta2 + 2*(A026 + A126*dr)*R2)*R4
        d2A_dR2 = 2*((A402 + A502*dr + (A602 + A702*dr)*dr2)*dr4 + ((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4)*dtheta2 + (A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2)* dtheta4) + 12*R2*((A204 + A304*dr)*dr2 + (A404 + A504*dr)*dr4 + (A024 + A124*dr + (A224 + A324*dr)*dr2)*dtheta2 + (A044 + A144*dr)*dtheta4 + (A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)* R2) + 18*(A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)*R4 + 56*(A008 + A108*dr)*R6
        d2A_dph2 = - T(0.25)*R*dA_dR + dR*dR*d2A_dR2
        d2A_dt2 = om*om*d2A_dph2
        d2A_dphdt = -om*d2A_dph2
        s2 = alpha20*dr2 + alpha02*dtheta2 + beta*R2
        ds2_dr = 2*alpha20*dr
        ds2_dth = 2*alpha02*dtheta
        ds2_dR = 2*beta*R
        ds2_dph = ds2_dR*dR
        ds2_dt = -om*ds2_dph
        d2s2_dr2 = 2*alpha20
        d2s2_dth2 = 2*alpha02
        d2s2_dR2 = 2*beta
        d2s2_dph2 = - T(0.25)*R*ds2_dR + dR*dR*d2s2_dR2
        d2s2_dt2 = om*om*d2s2_dph2
        d2s2_dphdt = -om*d2s2_dph2
        sqrts2 = sqrt(s2)
        s2_15 = s2*sqrts2
        s2_25 = s2*s2_15
        s2_35 = s2*s2_25
        s2_45 = s2*s2_35
        s2_55 = s2*s2_45
        PhiS_out = A/s2_35
        dPhiS_dt = (-7*ds2_dt*A + 2*dA_dt*s2)/(T(2.0)*s2_45)
        dPhiS_dr = (-7*ds2_dr*A + 2*dA_dr*s2) /(T(2.0)*s2_45)
        dPhiS_dth = (-7*ds2_dth*A + 2*dA_dth*s2)/(T(2.0)*s2_45)
        dPhiS_dph = (-7*ds2_dph*A + 2*dA_dph*s2)/(T(2.0)*s2_45)
        d2PhiS_dr2 = (63*ds2_dr*ds2_dr*A - 14*s2*(2*dA_dr*ds2_dr + d2s2_dr2*A) + 4*d2A_dr2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dth2 = (63*ds2_dth*ds2_dth*A - 14*s2*(2*dA_dth*ds2_dth + d2s2_dth2*A) + 4*d2A_dth2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dph2 = (63*ds2_dph*ds2_dph*A - 14*s2*(2*dA_dph*ds2_dph + d2s2_dph2*A) + 4*d2A_dph2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dt2 = (63*ds2_dt*ds2_dt*A - 14*s2*(2*dA_dt*ds2_dt + d2s2_dt2*A) + 4*d2A_dt2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dtph = (63*ds2_dph*ds2_dt*A - 14*s2*(dA_dt*ds2_dph + dA_dph*ds2_dt + d2s2_dphdt*A) + 4*d2A_dphdt*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dtr = T(NaN)
        d2PhiS_dtth = T(NaN)
        d2PhiS_drth = T(NaN)
        d2PhiS_drph = T(NaN)
        d2PhiS_dthph = T(NaN)
        sinth = sin(theta)
        sinth2 = sinth*sinth
        sin2th = sin(2*theta)
        cos2th = cos(2*theta)
        r2 = r*r
        r3 = r2*r
        r4 = r2*r2
        a2 = a*a
        a4 = a2*a2
        src_out = -(_csum(cm, 2*a2*dPhiS_dr, - a2*d2PhiS_dph2, - a4*d2PhiS_dr2, - a2*d2PhiS_dth2, - 4*dPhiS_dr*r, - 2*a2*dPhiS_dr*r, 4*d2PhiS_dph2*r, 2*a*d2PhiS_dtph*r, 4*a2*d2PhiS_dr2*r, 2*d2PhiS_dth2*r, 6*dPhiS_dr*r2, - 2*d2PhiS_dph2*r2, - 4*d2PhiS_dr2*r2, -
         2*a2*d2PhiS_dr2*r2, - d2PhiS_dth2*r2, - 2*dPhiS_dr*r3, 4*d2PhiS_dr2*r3, - d2PhiS_dr2*r4, (a4*d2PhiS_dt2 + 4*a*d2PhiS_dtph*r + 2*d2PhiS_dt2*r4 + a2*d2PhiS_dt2*r*(2 + 3*r))*sinth2, cos2th*(a4*d2PhiS_dr2 - 2*a*d2PhiS_dtph*r + (-2 + r)*r*(d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) + d2PhiS_dr2*(-2 + r)*r) +
            a2*(-d2PhiS_dph2 + d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) - 4*d2PhiS_dr2*r + 2*d2PhiS_dr2*r2) +
            a2*d2PhiS_dt2*(a2 + (-2 + r)*r)*sinth2), - a2*dPhiS_dth*sin2th, 2*dPhiS_dth*r*sin2th, -
         dPhiS_dth*r2*sin2th))/((sinth2*(a2 + (-2 + r)*r)*(a2 + 2*r2 + a2*cos2th)))
        dPhiS_dx[0] = dPhiS_dt
        dPhiS_dx[1] = dPhiS_dr
        dPhiS_dx[2] = dPhiS_dth
        dPhiS_dx[3] = dPhiS_dph
        d2PhiS_dx2[0] = d2PhiS_dt2
        d2PhiS_dx2[1] = d2PhiS_dtr
        d2PhiS_dx2[2] = d2PhiS_dtth
        d2PhiS_dx2[3] = d2PhiS_dtph
        d2PhiS_dx2[4] = d2PhiS_dr2
        d2PhiS_dx2[5] = d2PhiS_drth
        d2PhiS_dx2[6] = d2PhiS_drph
        d2PhiS_dx2[7] = d2PhiS_dth2
        d2PhiS_dx2[8] = d2PhiS_dthph
        d2PhiS_dx2[9] = d2PhiS_dph2
    return (PhiS_out,
            SVector{4,T}(dPhiS_dx[0], dPhiS_dx[1], dPhiS_dx[2], dPhiS_dx[3]),
            SVector{10,T}(d2PhiS_dx2[0], d2PhiS_dx2[1], d2PhiS_dx2[2], d2PhiS_dx2[3],
                          d2PhiS_dx2[4], d2PhiS_dx2[5], d2PhiS_dx2[6], d2PhiS_dx2[7],
                          d2PhiS_dx2[8], d2PhiS_dx2[9]),
            src_out)
end

"""calc at an `Offset` from the particle (avoids the r-rp cancellation)."""
calc(ctx::EffsourceCtx{T}, off::Offset{T}; comp::Bool=false) where {T} = _calc(ctx, off, Val(comp))
function _calc(ctx::EffsourceCtx{T}, off::Offset{T}, cm::Val) where {T}
    dPhiS_dx  = _ovec(T, 4)
    d2PhiS_dx2 = _ovec(T, 10)
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
    rp = xp.r
    thetap = xp.theta
    dr = off.dr
    dtheta = off.dtheta
    dphi = off.dphi
    r = rp + dr
    theta = thetap + dtheta
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr5 = dr3*dr2
        dr6 = dr3*dr3
        dr7 = dr4*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta3 = dtheta2*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta5 = dtheta3*dtheta2
        dtheta6 = dtheta3*dtheta3
        dtheta7 = dtheta4*dtheta3
        dtheta8 = dtheta4*dtheta4
        R = sin(T(0.5)*dphi)
        R2 = R*R
        R3 = R2*R
        R4 = R2*R2
        R5 = R3*R2
        R6 = R3*R3
        R7 = R4*R3
        R8 = R4*R4
        dR = T(0.5)*cos(T(0.5)*dphi)
        om = M / (a*M + sqrt(M*((rp)^(3))))
        A = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2) + (dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2))*R2 + (A008 + A108*dr)*R8 + R4*(dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4 + (A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2)*R2)
        #= return =#
        dA_dr = 6*(A600 + A700*dr)*dr5 + A700*dr6 + 8*(A800 + A900*dr)*dr7 + A900*dr8 + 4*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dr3*dtheta2 + (A520 + 2*dr*(A620 + A720*dr) + A720*dr2)*dr4*dtheta2 + (2*dr*(A240 + A340*dr) + A340*dr2 + 4*(A440 + A540*dr)*dr3 + A540*dr4 + (A160 + 2*dr*(A260 + A360*dr) + A360*dr2)*dtheta2)*dtheta4 + A180*dtheta8 + (4*(A402 + A502*dr + (A602 + A702*dr)*dr2)*dr3 + (A502 + 2*dr*(A602 + A702*dr) + A702*dr2)*dr4 + (2*dr*(A222 + A322*dr) + A322*dr2 + 4*(A422 + A522*dr)*dr3 + A522*dr4)* dtheta2 + (A142 + 2*dr*(A242 + A342*dr) + A342*dr2 + A162*dtheta2)* dtheta4)*R2 + (2*dr*(A204 + A304*dr) + A304*dr2 + 4*(A404 + A504*dr)*dr3 + A504*dr4 + (A124 + 2*dr*(A224 + A324*dr) + A324*dr2)*dtheta2 + A144*dtheta4 + (A106 + 2*dr*(A206 + A306*dr) + A306*dr2 + A126*dtheta2)*R2)* R4 + A108*R8
        dA_dth = 2*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dr4*dtheta + 4*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta2)*dtheta3 + 2*(A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta5 + 8*(A080 + A180*dr)*dtheta7 + (2*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4)*dtheta + 4*(A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2)* dtheta3 + 2*(A062 + A162*dr)*dtheta5)*R2 + (2*(A024 + A124*dr + (A224 + A324*dr)*dr2)*dtheta + 4*(A044 + A144*dr)*dtheta3 + 2*(A026 + A126*dr)*dtheta*R2)* R4
        dA_dR = 2*((A402 + A502*dr + (A602 + A702*dr)*dr2)*dr4 + ((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4)*dtheta2 + (A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2)* dtheta4)*R + 4*((A204 + A304*dr)*dr2 + (A404 + A504*dr)*dr4 + (A024 + A124*dr + (A224 + A324*dr)*dr2)*dtheta2 + (A044 + A144*dr)*dtheta4 + (A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)* R2)*R3 + 2*(A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)*R5 + 8*(A008 + A108*dr)*R7
        dA_dph = dA_dR*dR
        dA_dt = -om*dA_dph
        d2A_dr2 = 30*(A600 + A700*dr)*dr4 + 12*A700*dr5 + 56*(A800 + A900*dr)*dr6 + 16*A900*dr7 + 12*dr2*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dtheta2 + 8*(A520 + 2*dr*(A620 + A720*dr) + A720*dr2)*dr3*dtheta2 + (4*A720*dr + 2*(A620 + A720*dr))*dr4*dtheta2 + (4*A340*dr + 2*(A240 + A340*dr) + 12*(A440 + A540*dr)*dr2 + 8*A540*dr3 + (4*A360*dr + 2*(A260 + A360*dr))*dtheta2)*dtheta4 + (12*dr2*(A402 + A502*dr + (A602 + A702*dr)*dr2) + 8*(A502 + 2*dr*(A602 + A702*dr) + A702*dr2)*dr3 + (4*A702*dr + 2*(A602 + A702*dr))*dr4 + (4*A322*dr + 2*(A222 + A322*dr) + 12*(A422 + A522*dr)*dr2 + 8*A522*dr3)*dtheta2 + (4*A342*dr + 2*(A242 + A342*dr))*dtheta4)* R2 + (4*A304*dr + 2*(A204 + A304*dr) + 12*(A404 + A504*dr)*dr2 + 8*A504*dr3 + (4*A324*dr + 2*(A224 + A324*dr))*dtheta2 + (4*A306*dr + 2*(A206 + A306*dr))*R2)*R4
        d2A_dth2 = 2*(A420 + A520*dr + (A620 + A720*dr)*dr2)*dr4 + 12*dtheta2*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta2) + 18*(A060 + A160*dr + (A260 + A360*dr)*dr2)*dtheta4 + 56*(A080 + A180*dr)*dtheta6 + (2*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4) + 12*dtheta2*(A042 + A142*dr + (A242 + A342*dr)*dr2 +  (A062 + A162*dr)*dtheta2) + 18*(A062 + A162*dr)*dtheta4)*R2 + (2*(A024 + A124*dr + (A224 + A324*dr)*dr2) + 12*(A044 + A144*dr)*dtheta2 + 2*(A026 + A126*dr)*R2)*R4
        d2A_dR2 = 2*((A402 + A502*dr + (A602 + A702*dr)*dr2)*dr4 + ((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4)*dtheta2 + (A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2)* dtheta4) + 12*R2*((A204 + A304*dr)*dr2 + (A404 + A504*dr)*dr4 + (A024 + A124*dr + (A224 + A324*dr)*dr2)*dtheta2 + (A044 + A144*dr)*dtheta4 + (A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)* R2) + 18*(A006 + A106*dr + (A206 + A306*dr)*dr2 + (A026 + A126*dr)*dtheta2)*R4 + 56*(A008 + A108*dr)*R6
        d2A_dph2 = - T(0.25)*R*dA_dR + dR*dR*d2A_dR2
        d2A_dt2 = om*om*d2A_dph2
        d2A_dphdt = -om*d2A_dph2
        s2 = alpha20*dr2 + alpha02*dtheta2 + beta*R2
        ds2_dr = 2*alpha20*dr
        ds2_dth = 2*alpha02*dtheta
        ds2_dR = 2*beta*R
        ds2_dph = ds2_dR*dR
        ds2_dt = -om*ds2_dph
        d2s2_dr2 = 2*alpha20
        d2s2_dth2 = 2*alpha02
        d2s2_dR2 = 2*beta
        d2s2_dph2 = - T(0.25)*R*ds2_dR + dR*dR*d2s2_dR2
        d2s2_dt2 = om*om*d2s2_dph2
        d2s2_dphdt = -om*d2s2_dph2
        sqrts2 = sqrt(s2)
        s2_15 = s2*sqrts2
        s2_25 = s2*s2_15
        s2_35 = s2*s2_25
        s2_45 = s2*s2_35
        s2_55 = s2*s2_45
        PhiS_out = A/s2_35
        dPhiS_dt = (-7*ds2_dt*A + 2*dA_dt*s2)/(T(2.0)*s2_45)
        dPhiS_dr = (-7*ds2_dr*A + 2*dA_dr*s2) /(T(2.0)*s2_45)
        dPhiS_dth = (-7*ds2_dth*A + 2*dA_dth*s2)/(T(2.0)*s2_45)
        dPhiS_dph = (-7*ds2_dph*A + 2*dA_dph*s2)/(T(2.0)*s2_45)
        d2PhiS_dr2 = (63*ds2_dr*ds2_dr*A - 14*s2*(2*dA_dr*ds2_dr + d2s2_dr2*A) + 4*d2A_dr2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dth2 = (63*ds2_dth*ds2_dth*A - 14*s2*(2*dA_dth*ds2_dth + d2s2_dth2*A) + 4*d2A_dth2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dph2 = (63*ds2_dph*ds2_dph*A - 14*s2*(2*dA_dph*ds2_dph + d2s2_dph2*A) + 4*d2A_dph2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dt2 = (63*ds2_dt*ds2_dt*A - 14*s2*(2*dA_dt*ds2_dt + d2s2_dt2*A) + 4*d2A_dt2*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dtph = (63*ds2_dph*ds2_dt*A - 14*s2*(dA_dt*ds2_dph + dA_dph*ds2_dt + d2s2_dphdt*A) + 4*d2A_dphdt*s2*s2)/(T(4.0)*s2_55)
        d2PhiS_dtr = T(NaN)
        d2PhiS_dtth = T(NaN)
        d2PhiS_drth = T(NaN)
        d2PhiS_drph = T(NaN)
        d2PhiS_dthph = T(NaN)
        sinth = sin(theta)
        sinth2 = sinth*sinth
        sin2th = sin(2*theta)
        cos2th = cos(2*theta)
        r2 = r*r
        r3 = r2*r
        r4 = r2*r2
        a2 = a*a
        a4 = a2*a2
        src_out = -(_csum(cm, 2*a2*dPhiS_dr, - a2*d2PhiS_dph2, - a4*d2PhiS_dr2, - a2*d2PhiS_dth2, - 4*dPhiS_dr*r, - 2*a2*dPhiS_dr*r, 4*d2PhiS_dph2*r, 2*a*d2PhiS_dtph*r, 4*a2*d2PhiS_dr2*r, 2*d2PhiS_dth2*r, 6*dPhiS_dr*r2, - 2*d2PhiS_dph2*r2, - 4*d2PhiS_dr2*r2, -
         2*a2*d2PhiS_dr2*r2, - d2PhiS_dth2*r2, - 2*dPhiS_dr*r3, 4*d2PhiS_dr2*r3, - d2PhiS_dr2*r4, (a4*d2PhiS_dt2 + 4*a*d2PhiS_dtph*r + 2*d2PhiS_dt2*r4 + a2*d2PhiS_dt2*r*(2 + 3*r))*sinth2, cos2th*(a4*d2PhiS_dr2 - 2*a*d2PhiS_dtph*r + (-2 + r)*r*(d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) + d2PhiS_dr2*(-2 + r)*r) +
            a2*(-d2PhiS_dph2 + d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) - 4*d2PhiS_dr2*r + 2*d2PhiS_dr2*r2) +
            a2*d2PhiS_dt2*(a2 + (-2 + r)*r)*sinth2), - a2*dPhiS_dth*sin2th, 2*dPhiS_dth*r*sin2th, -
         dPhiS_dth*r2*sin2th))/((sinth2*(a2 + (-2 + r)*r)*(a2 + 2*r2 + a2*cos2th)))
        dPhiS_dx[0] = dPhiS_dt
        dPhiS_dx[1] = dPhiS_dr
        dPhiS_dx[2] = dPhiS_dth
        dPhiS_dx[3] = dPhiS_dph
        d2PhiS_dx2[0] = d2PhiS_dt2
        d2PhiS_dx2[1] = d2PhiS_dtr
        d2PhiS_dx2[2] = d2PhiS_dtth
        d2PhiS_dx2[3] = d2PhiS_dtph
        d2PhiS_dx2[4] = d2PhiS_dr2
        d2PhiS_dx2[5] = d2PhiS_drth
        d2PhiS_dx2[6] = d2PhiS_drph
        d2PhiS_dx2[7] = d2PhiS_dth2
        d2PhiS_dx2[8] = d2PhiS_dthph
        d2PhiS_dx2[9] = d2PhiS_dph2
    return (PhiS_out,
            SVector{4,T}(dPhiS_dx[0], dPhiS_dx[1], dPhiS_dx[2], dPhiS_dx[3]),
            SVector{10,T}(d2PhiS_dx2[0], d2PhiS_dx2[1], d2PhiS_dx2[2], d2PhiS_dx2[3],
                          d2PhiS_dx2[4], d2PhiS_dx2[5], d2PhiS_dx2[6], d2PhiS_dx2[7],
                          d2PhiS_dx2[8], d2PhiS_dx2[9]),
            src_out)
end

"""m-mode singular field (complex), including phase exp(-i m phi_p).
`comp=true` uses compensated summation for the numerator."""
phis_m(ctx::EffsourceCtx{T}, m::Integer, x::Coordinate{T}; comp::Bool=false) where {T} = _phis_m(ctx, m, x, Val(comp))
function _phis_m(ctx::EffsourceCtx{T}, m::Integer, x::Coordinate{T}, cm::Val) where {T}
    PhiS = _ovec(T, 2)
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
        A = _ovec(T, 5)
        r = x.r
        theta = x.theta
        rp = xp.r
        thetap = xp.theta
        dr = r - rp
        dtheta = theta - thetap
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr6 = dr3*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta8 = dtheta4*dtheta4
        A[0] = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2)
        A[1] = dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2)
        A[2] = dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4
        A[3] = A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2
        A[4] = A008 + A108*dr
        alpha = alpha20*dr2 + alpha02*dtheta2
        C1 = alpha / beta
        C = _ovec(T, 27)
        C[0] = 1
        C[1] = C1
        C[2] = C[1]*C[1]
        C[3] = C[2]*C[1]
        C[4] = C[2]*C[2]
        C[5] = C[3]*C[2]
        C[6] = C[3]*C[3]
        C[7] = C[4]*C[3]
        C[8] = C[4]*C[4]
        C[9] = C[5]*C[4]
        C[10] = C[5]*C[5]
        C[11] = C[6]*C[5]
        C[12] = C[6]*C[6]
        C[13] = C[7]*C[6]
        C[14] = C[7]*C[7]
        C[15] = C[8]*C[7]
        C[16] = C[8]*C[8]
        C[17] = C[9]*C[8]
        C[18] = C[9]*C[9]
        C[19] = C[10]*C[9]
        C[20] = C[10]*C[10]
        C[21] = C[11]*C[10]
        C[22] = C[11]*C[11]
        C[23] = C[12]*C[11]
        C[24] = C[12]*C[12]
        C[25] = C[13]*C[12]
        C[26] = C[13]*C[13]
        (ellK, ellE) = _ellKE_arg(C1)
        ellip = _ovec0(T[ellK, ellE])
        if m>20
            error("effsource: requested m-mode is not supported (m>20)")
        end
        num = zero(T)
        num_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    num, num_c = _cadd(cm, num, num_c, reei(T,m,i,j,k)*ellip[i]*A[j]*C[k])
                end
            end
        end
        num = num + num_c
        RePhiS = T(4.0)*num/(beta*C[3]*((alpha+beta)^(2) * sqrt(alpha+beta)))
        cosmph = cos(m*xp.phi)
        sinmph = sin(m*xp.phi)
        PhiS[0] = RePhiS*cosmph
        PhiS[1] = - RePhiS*sinmph
    return Complex(PhiS[0], PhiS[1])
end

"""phis_m at an `Offset` from the particle (avoids the r-rp cancellation)."""
phis_m(ctx::EffsourceCtx{T}, m::Integer, off::Offset{T}; comp::Bool=false) where {T} = _phis_m(ctx, m, off, Val(comp))
function _phis_m(ctx::EffsourceCtx{T}, m::Integer, off::Offset{T}, cm::Val) where {T}
    PhiS = _ovec(T, 2)
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
        A = _ovec(T, 5)
    rp = xp.r
    thetap = xp.theta
    dr = off.dr
    dtheta = off.dtheta
    r = rp + dr
    theta = thetap + dtheta
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr6 = dr3*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta8 = dtheta4*dtheta4
        A[0] = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2)
        A[1] = dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2)
        A[2] = dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4
        A[3] = A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2
        A[4] = A008 + A108*dr
        alpha = alpha20*dr2 + alpha02*dtheta2
        C1 = alpha / beta
        C = _ovec(T, 27)
        C[0] = 1
        C[1] = C1
        C[2] = C[1]*C[1]
        C[3] = C[2]*C[1]
        C[4] = C[2]*C[2]
        C[5] = C[3]*C[2]
        C[6] = C[3]*C[3]
        C[7] = C[4]*C[3]
        C[8] = C[4]*C[4]
        C[9] = C[5]*C[4]
        C[10] = C[5]*C[5]
        C[11] = C[6]*C[5]
        C[12] = C[6]*C[6]
        C[13] = C[7]*C[6]
        C[14] = C[7]*C[7]
        C[15] = C[8]*C[7]
        C[16] = C[8]*C[8]
        C[17] = C[9]*C[8]
        C[18] = C[9]*C[9]
        C[19] = C[10]*C[9]
        C[20] = C[10]*C[10]
        C[21] = C[11]*C[10]
        C[22] = C[11]*C[11]
        C[23] = C[12]*C[11]
        C[24] = C[12]*C[12]
        C[25] = C[13]*C[12]
        C[26] = C[13]*C[13]
        (ellK, ellE) = _ellKE_arg(C1)
        ellip = _ovec0(T[ellK, ellE])
        if m>20
            error("effsource: requested m-mode is not supported (m>20)")
        end
        num = zero(T)
        num_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    num, num_c = _cadd(cm, num, num_c, reei(T,m,i,j,k)*ellip[i]*A[j]*C[k])
                end
            end
        end
        num = num + num_c
        RePhiS = T(4.0)*num/(beta*C[3]*((alpha+beta)^(2) * sqrt(alpha+beta)))
        cosmph = cos(m*xp.phi)
        sinmph = sin(m*xp.phi)
        PhiS[0] = RePhiS*cosmph
        PhiS[1] = - RePhiS*sinmph
    return Complex(PhiS[0], PhiS[1])
end

"""m-mode singular field, derivatives and effective source (all complex).
Returns `(PhiS, dPhiS_dx[4], d2PhiS_dx2[10], src)`.
`comp=true` uses compensated summation for the numerator and source."""
calc_m(ctx::EffsourceCtx{T}, m::Integer, x::Coordinate{T}; comp::Bool=false) where {T} = _calc_m(ctx, m, x, Val(comp))
function _calc_m(ctx::EffsourceCtx{T}, m::Integer, x::Coordinate{T}, cm::Val) where {T}
    PhiS       = _ovec(T, 2)
    dPhiS_dx   = _ovec(T, 8)
    d2PhiS_dx2 = _ovec(T, 20)
    src        = _ovec(T, 2)
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
        A = _ovec(T, 5)
        dA_dr = _ovec(T, 5)
        d2A_dr2 = _ovec(T, 5)
        dA_dtheta = _ovec(T, 5)
        d2A_dtheta2 = _ovec(T, 5)
        r = x.r
        theta = x.theta
        rp = xp.r
        thetap = xp.theta
        om = M / (a*M + sqrt(M*((rp)^(3))))
        dr = r - rp
        dtheta = theta - thetap
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr5 = dr3*dr2
        dr6 = dr3*dr3
        dr7 = dr4*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta3 = dtheta2*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta5 = dtheta3*dtheta2
        dtheta6 = dtheta3*dtheta3
        dtheta7 = dtheta4*dtheta3
        dtheta8 = dtheta4*dtheta4
        A[0] = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2)
        A[1] = dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2)
        A[2] = dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4
        A[3] = A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2
        A[4] = A008 + A108*dr
        dA_dr[0] = 6*A600*dr5 + 7*A700*dr6 + 8*A800*dr7 + 9*A900*dr8 + 4*A420*dr3*dtheta2 + 5*A520*dr4*dtheta2 + 6*A620*dr5*dtheta2 + 7*A720*dr6*dtheta2 + 2*A240*dr*dtheta4 + 3*A340*dr2*dtheta4 + 4*A440*dr3*dtheta4 + 5*A540*dr4*dtheta4 + A160*dtheta6 + 2*A260*dr*dtheta6 + 3*A360*dr2*dtheta6 + A180*dtheta8
        dA_dr[1] = 4*A402*dr3 + 5*A502*dr4 + 6*A602*dr5 + 7*A702*dr6 + 2*A222*dr*dtheta2 + 3*A322*dr2*dtheta2 + 4*A422*dr3*dtheta2 + 5*A522*dr4*dtheta2 + A142*dtheta4 + 2*A242*dr*dtheta4 + 3*A342*dr2*dtheta4 + A162*dtheta6
        dA_dr[2] = 2*A204*dr + 3*A304*dr2 + 4*A404*dr3 + 5*A504*dr4 + A124*dtheta2 + 2*A224*dr*dtheta2 + 3*A324*dr2*dtheta2 + A144*dtheta4
        dA_dr[3] = A106 + 2*A206*dr + 3*A306*dr2 + A126*dtheta2
        dA_dr[4] = A108
        d2A_dr2[0] = 2*(15*A600*dr4 + 21*A700*dr5 + 28*A800*dr6 + 36*A900*dr7 + 6*A420*dr2*dtheta2 + 10*A520*dr3*dtheta2 + 15*A620*dr4*dtheta2 + 21*A720*dr5*dtheta2 + A240*dtheta4 + 3*A340*dr*dtheta4 + 6*A440*dr2*dtheta4 + 10*A540*dr3*dtheta4 + A260*dtheta6 + 3*A360*dr*dtheta6)
        d2A_dr2[1] = 2*(6*A402*dr2 + 10*A502*dr3 + 15*A602*dr4 + 21*A702*dr5 + A222*dtheta2 + 3*A322*dr*dtheta2 + 6*A422*dr2*dtheta2 + 10*A522*dr3*dtheta2 + A242*dtheta4 + 3*A342*dr*dtheta4)
        d2A_dr2[2] = 2*(A204 + 3*A304*dr + 6*A404*dr2 + 10*A504*dr3 + A224*dtheta2 + 3*A324*dr*dtheta2)
        d2A_dr2[3] = 2*(A206 + 3*A306*dr)
        d2A_dr2[4] = 0
        dA_dtheta[0] = 2*(A420 + dr*(A520 + dr*(A620 + A720*dr)))*dr4*dtheta + 4*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta2)*dtheta3 + 2*(A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta5 + 8*(A080 + A180*dr)*dtheta7
        dA_dtheta[1] = 2*dtheta*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4 + 2*dtheta2*(A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2) + (A062 + A162*dr)*dtheta4)
        dA_dtheta[2] = 2*dtheta*(A024 + A124*dr + (A224 + A324*dr)*dr2 + 2*(A044 + A144*dr)*dtheta2)
        dA_dtheta[3] = 2*(A026 + A126*dr)*dtheta
        dA_dtheta[4] = 0
        d2A_dtheta2[0] = 2*((A420 + dr*(A520 + dr*(A620 + A720*dr)))*dr4 + 6*dtheta2*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta2) + 9*(A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta4 + 28*(A080 + A180*dr)*dtheta6)
        d2A_dtheta2[1] = 2*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4 + 6*dtheta2*(A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2) + 9*(A062 + A162*dr)*dtheta4)
        d2A_dtheta2[2] = 2*(A024 + A124*dr + (A224 + A324*dr)*dr2 + 6*(A044 + A144*dr)*dtheta2)
        d2A_dtheta2[3] = 2*(A026 + A126*dr)
        d2A_dtheta2[4] = 0
        alpha = alpha20*dr2 + alpha02*dtheta2
        dalpha_dr = 2*alpha20*dr
        d2alpha_dr2 = 2*alpha20
        dalpha_dtheta = 2*alpha02*dtheta
        d2alpha_dtheta2 = 2*alpha02
        C1 = alpha / beta
        C = _ovec(T, 27)
        C[0] = 1
        C[1] = C1
        C[2] = C1*C1
        C[3] = C[2]*C[1]
        C[4] = C[2]*C[2]
        C[5] = C[3]*C[2]
        C[6] = C[3]*C[3]
        C[7] = C[4]*C[3]
        C[8] = C[4]*C[4]
        C[9] = C[5]*C[4]
        C[10] = C[5]*C[5]
        C[11] = C[6]*C[5]
        C[12] = C[6]*C[6]
        C[13] = C[7]*C[6]
        C[14] = C[7]*C[7]
        C[15] = C[8]*C[7]
        C[16] = C[8]*C[8]
        C[17] = C[9]*C[8]
        C[18] = C[9]*C[9]
        C[19] = C[10]*C[9]
        C[20] = C[10]*C[10]
        C[21] = C[11]*C[10]
        C[22] = C[11]*C[11]
        C[23] = C[12]*C[11]
        C[24] = C[12]*C[12]
        C[25] = C[13]*C[12]
        C[26] = C[13]*C[13]
        dC1_dr = dalpha_dr / beta
        d2C1_dr2 = d2alpha_dr2 / beta
        dC1_dtheta = dalpha_dtheta / beta
        d2C1_dtheta2 = d2alpha_dtheta2 / beta
        dC_dr = _ovec(T, 27)
        dC_dr[0] = 0
        dC_dr[1] = 1*C[0]*dC1_dr
        dC_dr[2] = 2*C[1]*dC1_dr
        dC_dr[3] = 3*C[2]*dC1_dr
        dC_dr[4] = 4*C[3]*dC1_dr
        dC_dr[5] = 5*C[4]*dC1_dr
        dC_dr[6] = 6*C[5]*dC1_dr
        dC_dr[7] = 7*C[6]*dC1_dr
        dC_dr[8] = 8*C[7]*dC1_dr
        dC_dr[9] = 9*C[8]*dC1_dr
        dC_dr[10] = 10*C[9]*dC1_dr
        dC_dr[11] = 11*C[10]*dC1_dr
        dC_dr[12] = 12*C[11]*dC1_dr
        dC_dr[13] = 13*C[12]*dC1_dr
        dC_dr[14] = 14*C[13]*dC1_dr
        dC_dr[15] = 15*C[14]*dC1_dr
        dC_dr[16] = 16*C[15]*dC1_dr
        dC_dr[17] = 17*C[16]*dC1_dr
        dC_dr[18] = 18*C[17]*dC1_dr
        dC_dr[19] = 19*C[18]*dC1_dr
        dC_dr[20] = 20*C[19]*dC1_dr
        dC_dr[21] = 21*C[20]*dC1_dr
        dC_dr[22] = 22*C[21]*dC1_dr
        dC_dr[23] = 23*C[22]*dC1_dr
        dC_dr[24] = 24*C[23]*dC1_dr
        dC_dr[25] = 25*C[24]*dC1_dr
        dC_dr[26] = 26*C[25]*dC1_dr
        d2C_dr2 = _ovec(T, 27)
        d2C_dr2[0] = 0
        d2C_dr2[1] = d2C1_dr2
        d2C_dr2[2] = 2*1*C[0]*dC1_dr*dC1_dr + 2*C[1]*d2C1_dr2
        d2C_dr2[3] = 3*2*C[1]*dC1_dr*dC1_dr + 3*C[2]*d2C1_dr2
        d2C_dr2[4] = 4*3*C[2]*dC1_dr*dC1_dr + 4*C[3]*d2C1_dr2
        d2C_dr2[5] = 5*4*C[3]*dC1_dr*dC1_dr + 5*C[4]*d2C1_dr2
        d2C_dr2[6] = 6*5*C[4]*dC1_dr*dC1_dr + 6*C[5]*d2C1_dr2
        d2C_dr2[7] = 7*6*C[5]*dC1_dr*dC1_dr + 7*C[6]*d2C1_dr2
        d2C_dr2[8] = 8*7*C[6]*dC1_dr*dC1_dr + 8*C[7]*d2C1_dr2
        d2C_dr2[9] = 9*8*C[7]*dC1_dr*dC1_dr + 9*C[8]*d2C1_dr2
        d2C_dr2[10] = 10*9*C[8]*dC1_dr*dC1_dr + 10*C[9]*d2C1_dr2
        d2C_dr2[11] = 11*10*C[9]*dC1_dr*dC1_dr + 11*C[10]*d2C1_dr2
        d2C_dr2[12] = 12*11*C[10]*dC1_dr*dC1_dr + 12*C[11]*d2C1_dr2
        d2C_dr2[13] = 13*12*C[11]*dC1_dr*dC1_dr + 13*C[12]*d2C1_dr2
        d2C_dr2[14] = 14*13*C[12]*dC1_dr*dC1_dr + 14*C[13]*d2C1_dr2
        d2C_dr2[15] = 15*14*C[13]*dC1_dr*dC1_dr + 15*C[14]*d2C1_dr2
        d2C_dr2[16] = 16*15*C[14]*dC1_dr*dC1_dr + 16*C[15]*d2C1_dr2
        d2C_dr2[17] = 17*16*C[15]*dC1_dr*dC1_dr + 17*C[16]*d2C1_dr2
        d2C_dr2[18] = 18*17*C[16]*dC1_dr*dC1_dr + 18*C[17]*d2C1_dr2
        d2C_dr2[19] = 19*18*C[17]*dC1_dr*dC1_dr + 19*C[18]*d2C1_dr2
        d2C_dr2[20] = 20*19*C[18]*dC1_dr*dC1_dr + 20*C[19]*d2C1_dr2
        d2C_dr2[21] = 21*20*C[19]*dC1_dr*dC1_dr + 21*C[20]*d2C1_dr2
        d2C_dr2[22] = 22*21*C[20]*dC1_dr*dC1_dr + 22*C[21]*d2C1_dr2
        d2C_dr2[23] = 23*22*C[21]*dC1_dr*dC1_dr + 23*C[22]*d2C1_dr2
        d2C_dr2[24] = 24*23*C[22]*dC1_dr*dC1_dr + 24*C[23]*d2C1_dr2
        d2C_dr2[25] = 25*24*C[23]*dC1_dr*dC1_dr + 25*C[24]*d2C1_dr2
        d2C_dr2[26] = 26*25*C[24]*dC1_dr*dC1_dr + 26*C[25]*d2C1_dr2
        dC_dtheta = _ovec(T, 27)
        dC_dtheta[0] = 0
        dC_dtheta[1] = 1*C[0]*dC1_dtheta
        dC_dtheta[2] = 2*C[1]*dC1_dtheta
        dC_dtheta[3] = 3*C[2]*dC1_dtheta
        dC_dtheta[4] = 4*C[3]*dC1_dtheta
        dC_dtheta[5] = 5*C[4]*dC1_dtheta
        dC_dtheta[6] = 6*C[5]*dC1_dtheta
        dC_dtheta[7] = 7*C[6]*dC1_dtheta
        dC_dtheta[8] = 8*C[7]*dC1_dtheta
        dC_dtheta[9] = 9*C[8]*dC1_dtheta
        dC_dtheta[10] = 10*C[9]*dC1_dtheta
        dC_dtheta[11] = 11*C[10]*dC1_dtheta
        dC_dtheta[12] = 12*C[11]*dC1_dtheta
        dC_dtheta[13] = 13*C[12]*dC1_dtheta
        dC_dtheta[14] = 14*C[13]*dC1_dtheta
        dC_dtheta[15] = 15*C[14]*dC1_dtheta
        dC_dtheta[16] = 16*C[15]*dC1_dtheta
        dC_dtheta[17] = 17*C[16]*dC1_dtheta
        dC_dtheta[18] = 18*C[17]*dC1_dtheta
        dC_dtheta[19] = 19*C[18]*dC1_dtheta
        dC_dtheta[20] = 20*C[19]*dC1_dtheta
        dC_dtheta[21] = 21*C[20]*dC1_dtheta
        dC_dtheta[22] = 22*C[21]*dC1_dtheta
        dC_dtheta[23] = 23*C[22]*dC1_dtheta
        dC_dtheta[24] = 24*C[23]*dC1_dtheta
        dC_dtheta[25] = 25*C[24]*dC1_dtheta
        dC_dtheta[26] = 26*C[25]*dC1_dtheta
        d2C_dtheta2 = _ovec(T, 27)
        d2C_dtheta2[0] = 0
        d2C_dtheta2[1] = d2C1_dtheta2
        d2C_dtheta2[2] = 2*1*C[0]*dC1_dtheta*dC1_dtheta + 2*C[1]*d2C1_dtheta2
        d2C_dtheta2[3] = 3*2*C[1]*dC1_dtheta*dC1_dtheta + 3*C[2]*d2C1_dtheta2
        d2C_dtheta2[4] = 4*3*C[2]*dC1_dtheta*dC1_dtheta + 4*C[3]*d2C1_dtheta2
        d2C_dtheta2[5] = 5*4*C[3]*dC1_dtheta*dC1_dtheta + 5*C[4]*d2C1_dtheta2
        d2C_dtheta2[6] = 6*5*C[4]*dC1_dtheta*dC1_dtheta + 6*C[5]*d2C1_dtheta2
        d2C_dtheta2[7] = 7*6*C[5]*dC1_dtheta*dC1_dtheta + 7*C[6]*d2C1_dtheta2
        d2C_dtheta2[8] = 8*7*C[6]*dC1_dtheta*dC1_dtheta + 8*C[7]*d2C1_dtheta2
        d2C_dtheta2[9] = 9*8*C[7]*dC1_dtheta*dC1_dtheta + 9*C[8]*d2C1_dtheta2
        d2C_dtheta2[10] = 10*9*C[8]*dC1_dtheta*dC1_dtheta + 10*C[9]*d2C1_dtheta2
        d2C_dtheta2[11] = 11*10*C[9]*dC1_dtheta*dC1_dtheta + 11*C[10]*d2C1_dtheta2
        d2C_dtheta2[12] = 12*11*C[10]*dC1_dtheta*dC1_dtheta + 12*C[11]*d2C1_dtheta2
        d2C_dtheta2[13] = 13*12*C[11]*dC1_dtheta*dC1_dtheta + 13*C[12]*d2C1_dtheta2
        d2C_dtheta2[14] = 14*13*C[12]*dC1_dtheta*dC1_dtheta + 14*C[13]*d2C1_dtheta2
        d2C_dtheta2[15] = 15*14*C[13]*dC1_dtheta*dC1_dtheta + 15*C[14]*d2C1_dtheta2
        d2C_dtheta2[16] = 16*15*C[14]*dC1_dtheta*dC1_dtheta + 16*C[15]*d2C1_dtheta2
        d2C_dtheta2[17] = 17*16*C[15]*dC1_dtheta*dC1_dtheta + 17*C[16]*d2C1_dtheta2
        d2C_dtheta2[18] = 18*17*C[16]*dC1_dtheta*dC1_dtheta + 18*C[17]*d2C1_dtheta2
        d2C_dtheta2[19] = 19*18*C[17]*dC1_dtheta*dC1_dtheta + 19*C[18]*d2C1_dtheta2
        d2C_dtheta2[20] = 20*19*C[18]*dC1_dtheta*dC1_dtheta + 20*C[19]*d2C1_dtheta2
        d2C_dtheta2[21] = 21*20*C[19]*dC1_dtheta*dC1_dtheta + 21*C[20]*d2C1_dtheta2
        d2C_dtheta2[22] = 22*21*C[20]*dC1_dtheta*dC1_dtheta + 22*C[21]*d2C1_dtheta2
        d2C_dtheta2[23] = 23*22*C[21]*dC1_dtheta*dC1_dtheta + 23*C[22]*d2C1_dtheta2
        d2C_dtheta2[24] = 24*23*C[22]*dC1_dtheta*dC1_dtheta + 24*C[23]*d2C1_dtheta2
        d2C_dtheta2[25] = 25*24*C[23]*dC1_dtheta*dC1_dtheta + 25*C[24]*d2C1_dtheta2
        d2C_dtheta2[26] = 26*25*C[24]*dC1_dtheta*dC1_dtheta + 26*C[25]*d2C1_dtheta2
        (ellK, ellE) = _ellKE_arg(C1)
        ellip = _ovec0(T[ellK, ellE])
        dellE_dC = (ellK - ellE)/(T(2.0)*(1+C1))
        dellK_dC = (C1*ellK - (1+C1)*ellE)/(T(2.0)*C1*(1+C1))
        d2ellE_dC2 = -(2*C1*ellK - (2*C1-1)*ellE)/(T(4.0)*C1*(1+C1)*(1+C1))
        d2ellK_dC2 = -(C1*(1+2*C1)*ellK - 2*(1+C1)*(1+C1)*ellE)/(T(4.0)*C1*C1*(1+C1)*(1+C1))
        dellE_dr = dellE_dC * dC1_dr
        dellE_dtheta = dellE_dC * dC1_dtheta
        d2ellE_dr2 = d2ellE_dC2 * dC1_dr * dC1_dr + dellE_dC * d2C1_dr2
        d2ellE_dtheta2 = d2ellE_dC2 * dC1_dtheta * dC1_dtheta + dellE_dC * d2C1_dtheta2
        dellK_dr = dellK_dC * dC1_dr
        dellK_dtheta = dellK_dC * dC1_dtheta
        d2ellK_dr2 = d2ellK_dC2 * dC1_dr * dC1_dr + dellK_dC * d2C1_dr2
        d2ellK_dtheta2 = d2ellK_dC2 * dC1_dtheta * dC1_dtheta + dellK_dC * d2C1_dtheta2
        dellip_dr = _ovec0(T[dellK_dr, dellE_dr])
        dellip_dtheta = _ovec0(T[dellK_dtheta, dellE_dtheta])
        d2ellip_dr2 = _ovec0(T[d2ellK_dr2, d2ellE_dr2])
        d2ellip_dtheta2 = _ovec0(T[d2ellK_dtheta2, d2ellE_dtheta2])
        if m>20
            error("effsource: requested m-mode is not supported (m>20)")
        end
        num = zero(T)
        num_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    num, num_c = _cadd(cm, num, num_c, reei(T,m,i,j,k)*ellip[i]*A[j]*C[k])
                end
            end
        end
        num = num + num_c
        dnum_dr = zero(T)
        dnum_dr_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    dnum_dr, dnum_dr_c = _cadd(cm, dnum_dr, dnum_dr_c, reei(T,m,i,j,k)*
            (dellip_dr[i]*A[j]*C[k]
           + ellip[i]*dA_dr[j]*C[k]
           + ellip[i]*A[j]*dC_dr[k]))
                end
            end
        end
        dnum_dr = dnum_dr + dnum_dr_c
        d2num_dr2 = zero(T)
        d2num_dr2_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    d2num_dr2, d2num_dr2_c = _cadd(cm, d2num_dr2, d2num_dr2_c, reei(T,m,i,j,k)*
            (d2ellip_dr2[i]*A[j]*C[k]
           + dellip_dr[i]*dA_dr[j]*C[k]
           + dellip_dr[i]*A[j]*dC_dr[k]
           + dellip_dr[i]*dA_dr[j]*C[k]
           + ellip[i]*d2A_dr2[j]*C[k]
           + ellip[i]*dA_dr[j]*dC_dr[k]
           + dellip_dr[i]*A[j]*dC_dr[k]
           + ellip[i]*dA_dr[j]*dC_dr[k]
           + ellip[i]*A[j]*d2C_dr2[k]))
                end
            end
        end
        d2num_dr2 = d2num_dr2 + d2num_dr2_c
        dnum_dtheta = zero(T)
        dnum_dtheta_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    dnum_dtheta, dnum_dtheta_c = _cadd(cm, dnum_dtheta, dnum_dtheta_c, reei(T,m,i,j,k)*
            (dellip_dtheta[i]*A[j]*C[k]
           + ellip[i]*dA_dtheta[j]*C[k]
           + ellip[i]*A[j]*dC_dtheta[k]))
                end
            end
        end
        dnum_dtheta = dnum_dtheta + dnum_dtheta_c
        d2num_dtheta2 = zero(T)
        d2num_dtheta2_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    d2num_dtheta2, d2num_dtheta2_c = _cadd(cm, d2num_dtheta2, d2num_dtheta2_c, reei(T,m,i,j,k)*
            (d2ellip_dtheta2[i]*A[j]*C[k]
           + dellip_dtheta[i]*dA_dtheta[j]*C[k]
           + dellip_dtheta[i]*A[j]*dC_dtheta[k]
           + dellip_dtheta[i]*dA_dtheta[j]*C[k]
           + ellip[i]*d2A_dtheta2[j]*C[k]
           + ellip[i]*dA_dtheta[j]*dC_dtheta[k]
           + dellip_dtheta[i]*A[j]*dC_dtheta[k]
           + ellip[i]*dA_dtheta[j]*dC_dtheta[k]
           + ellip[i]*A[j]*d2C_dtheta2[k]))
                end
            end
        end
        d2num_dtheta2 = d2num_dtheta2 + d2num_dtheta2_c
        s = beta*C[3]*((alpha+beta)^(2) * sqrt(alpha+beta))
        ds_dr = beta*(3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dr + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dr)
        ds_dtheta = beta*(3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dtheta + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dtheta)
        d2s_dr2 = beta*(6*C1*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dr*dC1_dr
               + 3*C[2]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dr*dC1_dr
               + 3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*d2C1_dr2
               + 3*C[2]*dC1_dr*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dr
               + C[3]*T(2.5)*T(1.5)*((alpha+beta)^(0) * sqrt(alpha+beta))*dalpha_dr*dalpha_dr
               + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*d2alpha_dr2)
        d2s_dtheta2 = beta*(6*C1*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dtheta*dC1_dtheta
               + 3*C[2]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dtheta*dC1_dtheta
               + 3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*d2C1_dtheta2
               + 3*C[2]*dC1_dtheta*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dtheta
               + C[3]*T(2.5)*T(1.5)*((alpha+beta)^(0) * sqrt(alpha+beta))*dalpha_dtheta*dalpha_dtheta
               + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*d2alpha_dtheta2)
        RePhiS = T(4.0)*num/s
        dPhiS_dt = - m * om * (RePhiS)
        dPhiS_dr = T(4.0)*(-ds_dr*num + dnum_dr*s) /(s*s)
        dPhiS_dth = T(4.0)*(-ds_dtheta*num + dnum_dtheta*s)/(s*s)
        dPhiS_dph = m * (RePhiS)
        d2PhiS_dr2 = T(4.0)*(T(2.0)*ds_dr*ds_dr*num - s*(2*dnum_dr*ds_dr + d2s_dr2*num) + d2num_dr2*s*s)/(s*s*s)
        d2PhiS_dth2 = T(4.0)*(T(2.0)*ds_dtheta*ds_dtheta*num - s*(2*dnum_dtheta*ds_dtheta + d2s_dtheta2*num) + d2num_dtheta2*s*s)/(s*s*s)
        d2PhiS_dph2 = - m*m*(RePhiS)
        d2PhiS_dt2 = - m*m*om*om*(RePhiS)
        d2PhiS_dtph = m*m*om*(RePhiS)
        d2PhiS_dtr = T(NaN)
        d2PhiS_dtth = T(NaN)
        d2PhiS_drth = T(NaN)
        d2PhiS_drph = T(NaN)
        d2PhiS_dthph = T(NaN)
        sinth = sin(theta)
        sinth2 = sinth*sinth
        sin2th = sin(2*theta)
        cos2th = cos(2*theta)
        r2 = r*r
        r3 = r2*r
        r4 = r2*r2
        a2 = a*a
        a4 = a2*a2
        effsrc = -(_csum(cm, 2*a2*dPhiS_dr, - a2*d2PhiS_dph2, - a4*d2PhiS_dr2, - a2*d2PhiS_dth2, - 4*dPhiS_dr*r, - 2*a2*dPhiS_dr*r, 4*d2PhiS_dph2*r, 2*a*d2PhiS_dtph*r, 4*a2*d2PhiS_dr2*r, 2*d2PhiS_dth2*r, 6*dPhiS_dr*r2, - 2*d2PhiS_dph2*r2, - 4*d2PhiS_dr2*r2, -
         2*a2*d2PhiS_dr2*r2, - d2PhiS_dth2*r2, - 2*dPhiS_dr*r3, 4*d2PhiS_dr2*r3, - d2PhiS_dr2*r4, (a4*d2PhiS_dt2 + 4*a*d2PhiS_dtph*r + 2*d2PhiS_dt2*r4 + a2*d2PhiS_dt2*r*(2 + 3*r))*sinth2, cos2th*(a4*d2PhiS_dr2 - 2*a*d2PhiS_dtph*r + (-2 + r)*r*(d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) + d2PhiS_dr2*(-2 + r)*r) +
            a2*(-d2PhiS_dph2 + d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) - 4*d2PhiS_dr2*r + 2*d2PhiS_dr2*r2) +
            a2*d2PhiS_dt2*(a2 + (-2 + r)*r)*sinth2), - a2*dPhiS_dth*sin2th, 2*dPhiS_dth*r*sin2th, -
         dPhiS_dth*r2*sin2th))/((sinth2*(a2 + (-2 + r)*r)*(a2 + 2*r2 + a2*cos2th)))
        cosmph = cos(m*xp.phi)
        sinmph = sin(m*xp.phi)
        PhiS[0] = RePhiS*cosmph
        PhiS[1] = - RePhiS*sinmph
        dPhiS_dx[0] = dPhiS_dt*sinmph
        dPhiS_dx[1] = dPhiS_dt*cosmph
        dPhiS_dx[2] = dPhiS_dr*cosmph
        dPhiS_dx[3] = - dPhiS_dr*sinmph
        dPhiS_dx[4] = dPhiS_dth*cosmph
        dPhiS_dx[5] = - dPhiS_dth*sinmph
        dPhiS_dx[6] = dPhiS_dph*sinmph
        dPhiS_dx[7] = dPhiS_dph*cosmph
        d2PhiS_dx2[0] = d2PhiS_dt2*cosmph
        d2PhiS_dx2[1] = - d2PhiS_dt2*sinmph
        d2PhiS_dx2[2] = d2PhiS_dtr*cosmph
        d2PhiS_dx2[3] = - d2PhiS_dtr*sinmph
        d2PhiS_dx2[4] = d2PhiS_dtth*cosmph
        d2PhiS_dx2[5] = - d2PhiS_dtth*sinmph
        d2PhiS_dx2[6] = d2PhiS_dtph*cosmph
        d2PhiS_dx2[7] = - d2PhiS_dtph*sinmph
        d2PhiS_dx2[8] = d2PhiS_dr2*cosmph
        d2PhiS_dx2[9] = - d2PhiS_dr2*sinmph
        d2PhiS_dx2[10] = d2PhiS_drth*cosmph
        d2PhiS_dx2[11] = - d2PhiS_drth*sinmph
        d2PhiS_dx2[12] = d2PhiS_drph*cosmph
        d2PhiS_dx2[13] = - d2PhiS_drph*sinmph
        d2PhiS_dx2[14] = d2PhiS_dth2*cosmph
        d2PhiS_dx2[15] = - d2PhiS_dth2*sinmph
        d2PhiS_dx2[16] = d2PhiS_dthph*cosmph
        d2PhiS_dx2[17] = - d2PhiS_dthph*sinmph
        d2PhiS_dx2[18] = d2PhiS_dph2*cosmph
        d2PhiS_dx2[19] = - d2PhiS_dph2*sinmph
        src[0] = effsrc*cosmph
        src[1] = - effsrc*sinmph
    return (Complex(PhiS[0], PhiS[1]),
            SVector{4,Complex{T}}(Complex(dPhiS_dx[0], dPhiS_dx[1]),
                                  Complex(dPhiS_dx[2], dPhiS_dx[3]),
                                  Complex(dPhiS_dx[4], dPhiS_dx[5]),
                                  Complex(dPhiS_dx[6], dPhiS_dx[7])),
            SVector{10,Complex{T}}(Complex(d2PhiS_dx2[0], d2PhiS_dx2[1]),
                                   Complex(d2PhiS_dx2[2], d2PhiS_dx2[3]),
                                   Complex(d2PhiS_dx2[4], d2PhiS_dx2[5]),
                                   Complex(d2PhiS_dx2[6], d2PhiS_dx2[7]),
                                   Complex(d2PhiS_dx2[8], d2PhiS_dx2[9]),
                                   Complex(d2PhiS_dx2[10], d2PhiS_dx2[11]),
                                   Complex(d2PhiS_dx2[12], d2PhiS_dx2[13]),
                                   Complex(d2PhiS_dx2[14], d2PhiS_dx2[15]),
                                   Complex(d2PhiS_dx2[16], d2PhiS_dx2[17]),
                                   Complex(d2PhiS_dx2[18], d2PhiS_dx2[19])),
            Complex(src[0], src[1]))
end

"""calc_m at an `Offset` from the particle (avoids the r-rp cancellation)."""
calc_m(ctx::EffsourceCtx{T}, m::Integer, off::Offset{T}; comp::Bool=false) where {T} = _calc_m(ctx, m, off, Val(comp))
function _calc_m(ctx::EffsourceCtx{T}, m::Integer, off::Offset{T}, cm::Val) where {T}
    PhiS       = _ovec(T, 2)
    dPhiS_dx   = _ovec(T, 8)
    d2PhiS_dx2 = _ovec(T, 20)
    src        = _ovec(T, 2)
        M = ctx.M
        a = ctx.a
        xp = ctx.xp
        A006 = ctx.A006
        A008 = ctx.A008
        A024 = ctx.A024
        A026 = ctx.A026
        A042 = ctx.A042
        A044 = ctx.A044
        A060 = ctx.A060
        A062 = ctx.A062
        A080 = ctx.A080
        A106 = ctx.A106
        A108 = ctx.A108
        A124 = ctx.A124
        A126 = ctx.A126
        A142 = ctx.A142
        A144 = ctx.A144
        A160 = ctx.A160
        A162 = ctx.A162
        A180 = ctx.A180
        A204 = ctx.A204
        A206 = ctx.A206
        A222 = ctx.A222
        A224 = ctx.A224
        A240 = ctx.A240
        A242 = ctx.A242
        A260 = ctx.A260
        A304 = ctx.A304
        A306 = ctx.A306
        A322 = ctx.A322
        A324 = ctx.A324
        A340 = ctx.A340
        A342 = ctx.A342
        A360 = ctx.A360
        A402 = ctx.A402
        A404 = ctx.A404
        A420 = ctx.A420
        A422 = ctx.A422
        A440 = ctx.A440
        A502 = ctx.A502
        A504 = ctx.A504
        A520 = ctx.A520
        A522 = ctx.A522
        A540 = ctx.A540
        A600 = ctx.A600
        A602 = ctx.A602
        A620 = ctx.A620
        A700 = ctx.A700
        A702 = ctx.A702
        A720 = ctx.A720
        A800 = ctx.A800
        A900 = ctx.A900
        alpha20 = ctx.alpha20
        alpha02 = ctx.alpha02
        beta = ctx.beta
        A = _ovec(T, 5)
        dA_dr = _ovec(T, 5)
        d2A_dr2 = _ovec(T, 5)
        dA_dtheta = _ovec(T, 5)
        d2A_dtheta2 = _ovec(T, 5)
    rp = xp.r
    thetap = xp.theta
    dr = off.dr
    dtheta = off.dtheta
    r = rp + dr
    theta = thetap + dtheta
        om = M / (a*M + sqrt(M*((rp)^(3))))
        dr2 = dr*dr
        dr3 = dr2*dr
        dr4 = dr2*dr2
        dr5 = dr3*dr2
        dr6 = dr3*dr3
        dr7 = dr4*dr3
        dr8 = dr4*dr4
        dtheta2 = dtheta*dtheta
        dtheta3 = dtheta2*dtheta
        dtheta4 = dtheta2*dtheta2
        dtheta5 = dtheta3*dtheta2
        dtheta6 = dtheta3*dtheta3
        dtheta7 = dtheta4*dtheta3
        dtheta8 = dtheta4*dtheta4
        A[0] = dr6*(A600 + A700*dr) + dr8*(A800 + A900*dr) + dr4*(A420 + A520*dr + dr2*(A620 + A720*dr))*dtheta2 + (A080 + A180*dr)*dtheta8 + dtheta4*(dr2*(A240 + A340*dr) + dr4*(A440 + A540*dr) + (A060 + A160*dr + dr2*(A260 + A360*dr))*dtheta2)
        A[1] = dr4*(A402 + A502*dr + dr2*(A602 + A702*dr)) + (dr2*(A222 + A322*dr) + dr4*(A422 + A522*dr))*dtheta2 + dtheta4*(A042 + A142*dr + dr2*(A242 + A342*dr) + (A062 + A162*dr)*dtheta2)
        A[2] = dr2*(A204 + A304*dr) + dr4*(A404 + A504*dr) + (A024 + A124*dr + dr2*(A224 + A324*dr))*dtheta2 + (A044 + A144*dr)*dtheta4
        A[3] = A006 + A106*dr + dr2*(A206 + A306*dr) + (A026 + A126*dr)*dtheta2
        A[4] = A008 + A108*dr
        dA_dr[0] = 6*A600*dr5 + 7*A700*dr6 + 8*A800*dr7 + 9*A900*dr8 + 4*A420*dr3*dtheta2 + 5*A520*dr4*dtheta2 + 6*A620*dr5*dtheta2 + 7*A720*dr6*dtheta2 + 2*A240*dr*dtheta4 + 3*A340*dr2*dtheta4 + 4*A440*dr3*dtheta4 + 5*A540*dr4*dtheta4 + A160*dtheta6 + 2*A260*dr*dtheta6 + 3*A360*dr2*dtheta6 + A180*dtheta8
        dA_dr[1] = 4*A402*dr3 + 5*A502*dr4 + 6*A602*dr5 + 7*A702*dr6 + 2*A222*dr*dtheta2 + 3*A322*dr2*dtheta2 + 4*A422*dr3*dtheta2 + 5*A522*dr4*dtheta2 + A142*dtheta4 + 2*A242*dr*dtheta4 + 3*A342*dr2*dtheta4 + A162*dtheta6
        dA_dr[2] = 2*A204*dr + 3*A304*dr2 + 4*A404*dr3 + 5*A504*dr4 + A124*dtheta2 + 2*A224*dr*dtheta2 + 3*A324*dr2*dtheta2 + A144*dtheta4
        dA_dr[3] = A106 + 2*A206*dr + 3*A306*dr2 + A126*dtheta2
        dA_dr[4] = A108
        d2A_dr2[0] = 2*(15*A600*dr4 + 21*A700*dr5 + 28*A800*dr6 + 36*A900*dr7 + 6*A420*dr2*dtheta2 + 10*A520*dr3*dtheta2 + 15*A620*dr4*dtheta2 + 21*A720*dr5*dtheta2 + A240*dtheta4 + 3*A340*dr*dtheta4 + 6*A440*dr2*dtheta4 + 10*A540*dr3*dtheta4 + A260*dtheta6 + 3*A360*dr*dtheta6)
        d2A_dr2[1] = 2*(6*A402*dr2 + 10*A502*dr3 + 15*A602*dr4 + 21*A702*dr5 + A222*dtheta2 + 3*A322*dr*dtheta2 + 6*A422*dr2*dtheta2 + 10*A522*dr3*dtheta2 + A242*dtheta4 + 3*A342*dr*dtheta4)
        d2A_dr2[2] = 2*(A204 + 3*A304*dr + 6*A404*dr2 + 10*A504*dr3 + A224*dtheta2 + 3*A324*dr*dtheta2)
        d2A_dr2[3] = 2*(A206 + 3*A306*dr)
        d2A_dr2[4] = 0
        dA_dtheta[0] = 2*(A420 + dr*(A520 + dr*(A620 + A720*dr)))*dr4*dtheta + 4*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta2)*dtheta3 + 2*(A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta5 + 8*(A080 + A180*dr)*dtheta7
        dA_dtheta[1] = 2*dtheta*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4 + 2*dtheta2*(A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2) + (A062 + A162*dr)*dtheta4)
        dA_dtheta[2] = 2*dtheta*(A024 + A124*dr + (A224 + A324*dr)*dr2 + 2*(A044 + A144*dr)*dtheta2)
        dA_dtheta[3] = 2*(A026 + A126*dr)*dtheta
        dA_dtheta[4] = 0
        d2A_dtheta2[0] = 2*((A420 + dr*(A520 + dr*(A620 + A720*dr)))*dr4 + 6*dtheta2*((A240 + A340*dr)*dr2 + (A440 + A540*dr)*dr4 + (A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta2) + 9*(A060 + dr*(A160 + dr*(A260 + A360*dr)))*dtheta4 + 28*(A080 + A180*dr)*dtheta6)
        d2A_dtheta2[1] = 2*((A222 + A322*dr)*dr2 + (A422 + A522*dr)*dr4 + 6*dtheta2*(A042 + A142*dr + (A242 + A342*dr)*dr2 + (A062 + A162*dr)*dtheta2) + 9*(A062 + A162*dr)*dtheta4)
        d2A_dtheta2[2] = 2*(A024 + A124*dr + (A224 + A324*dr)*dr2 + 6*(A044 + A144*dr)*dtheta2)
        d2A_dtheta2[3] = 2*(A026 + A126*dr)
        d2A_dtheta2[4] = 0
        alpha = alpha20*dr2 + alpha02*dtheta2
        dalpha_dr = 2*alpha20*dr
        d2alpha_dr2 = 2*alpha20
        dalpha_dtheta = 2*alpha02*dtheta
        d2alpha_dtheta2 = 2*alpha02
        C1 = alpha / beta
        C = _ovec(T, 27)
        C[0] = 1
        C[1] = C1
        C[2] = C1*C1
        C[3] = C[2]*C[1]
        C[4] = C[2]*C[2]
        C[5] = C[3]*C[2]
        C[6] = C[3]*C[3]
        C[7] = C[4]*C[3]
        C[8] = C[4]*C[4]
        C[9] = C[5]*C[4]
        C[10] = C[5]*C[5]
        C[11] = C[6]*C[5]
        C[12] = C[6]*C[6]
        C[13] = C[7]*C[6]
        C[14] = C[7]*C[7]
        C[15] = C[8]*C[7]
        C[16] = C[8]*C[8]
        C[17] = C[9]*C[8]
        C[18] = C[9]*C[9]
        C[19] = C[10]*C[9]
        C[20] = C[10]*C[10]
        C[21] = C[11]*C[10]
        C[22] = C[11]*C[11]
        C[23] = C[12]*C[11]
        C[24] = C[12]*C[12]
        C[25] = C[13]*C[12]
        C[26] = C[13]*C[13]
        dC1_dr = dalpha_dr / beta
        d2C1_dr2 = d2alpha_dr2 / beta
        dC1_dtheta = dalpha_dtheta / beta
        d2C1_dtheta2 = d2alpha_dtheta2 / beta
        dC_dr = _ovec(T, 27)
        dC_dr[0] = 0
        dC_dr[1] = 1*C[0]*dC1_dr
        dC_dr[2] = 2*C[1]*dC1_dr
        dC_dr[3] = 3*C[2]*dC1_dr
        dC_dr[4] = 4*C[3]*dC1_dr
        dC_dr[5] = 5*C[4]*dC1_dr
        dC_dr[6] = 6*C[5]*dC1_dr
        dC_dr[7] = 7*C[6]*dC1_dr
        dC_dr[8] = 8*C[7]*dC1_dr
        dC_dr[9] = 9*C[8]*dC1_dr
        dC_dr[10] = 10*C[9]*dC1_dr
        dC_dr[11] = 11*C[10]*dC1_dr
        dC_dr[12] = 12*C[11]*dC1_dr
        dC_dr[13] = 13*C[12]*dC1_dr
        dC_dr[14] = 14*C[13]*dC1_dr
        dC_dr[15] = 15*C[14]*dC1_dr
        dC_dr[16] = 16*C[15]*dC1_dr
        dC_dr[17] = 17*C[16]*dC1_dr
        dC_dr[18] = 18*C[17]*dC1_dr
        dC_dr[19] = 19*C[18]*dC1_dr
        dC_dr[20] = 20*C[19]*dC1_dr
        dC_dr[21] = 21*C[20]*dC1_dr
        dC_dr[22] = 22*C[21]*dC1_dr
        dC_dr[23] = 23*C[22]*dC1_dr
        dC_dr[24] = 24*C[23]*dC1_dr
        dC_dr[25] = 25*C[24]*dC1_dr
        dC_dr[26] = 26*C[25]*dC1_dr
        d2C_dr2 = _ovec(T, 27)
        d2C_dr2[0] = 0
        d2C_dr2[1] = d2C1_dr2
        d2C_dr2[2] = 2*1*C[0]*dC1_dr*dC1_dr + 2*C[1]*d2C1_dr2
        d2C_dr2[3] = 3*2*C[1]*dC1_dr*dC1_dr + 3*C[2]*d2C1_dr2
        d2C_dr2[4] = 4*3*C[2]*dC1_dr*dC1_dr + 4*C[3]*d2C1_dr2
        d2C_dr2[5] = 5*4*C[3]*dC1_dr*dC1_dr + 5*C[4]*d2C1_dr2
        d2C_dr2[6] = 6*5*C[4]*dC1_dr*dC1_dr + 6*C[5]*d2C1_dr2
        d2C_dr2[7] = 7*6*C[5]*dC1_dr*dC1_dr + 7*C[6]*d2C1_dr2
        d2C_dr2[8] = 8*7*C[6]*dC1_dr*dC1_dr + 8*C[7]*d2C1_dr2
        d2C_dr2[9] = 9*8*C[7]*dC1_dr*dC1_dr + 9*C[8]*d2C1_dr2
        d2C_dr2[10] = 10*9*C[8]*dC1_dr*dC1_dr + 10*C[9]*d2C1_dr2
        d2C_dr2[11] = 11*10*C[9]*dC1_dr*dC1_dr + 11*C[10]*d2C1_dr2
        d2C_dr2[12] = 12*11*C[10]*dC1_dr*dC1_dr + 12*C[11]*d2C1_dr2
        d2C_dr2[13] = 13*12*C[11]*dC1_dr*dC1_dr + 13*C[12]*d2C1_dr2
        d2C_dr2[14] = 14*13*C[12]*dC1_dr*dC1_dr + 14*C[13]*d2C1_dr2
        d2C_dr2[15] = 15*14*C[13]*dC1_dr*dC1_dr + 15*C[14]*d2C1_dr2
        d2C_dr2[16] = 16*15*C[14]*dC1_dr*dC1_dr + 16*C[15]*d2C1_dr2
        d2C_dr2[17] = 17*16*C[15]*dC1_dr*dC1_dr + 17*C[16]*d2C1_dr2
        d2C_dr2[18] = 18*17*C[16]*dC1_dr*dC1_dr + 18*C[17]*d2C1_dr2
        d2C_dr2[19] = 19*18*C[17]*dC1_dr*dC1_dr + 19*C[18]*d2C1_dr2
        d2C_dr2[20] = 20*19*C[18]*dC1_dr*dC1_dr + 20*C[19]*d2C1_dr2
        d2C_dr2[21] = 21*20*C[19]*dC1_dr*dC1_dr + 21*C[20]*d2C1_dr2
        d2C_dr2[22] = 22*21*C[20]*dC1_dr*dC1_dr + 22*C[21]*d2C1_dr2
        d2C_dr2[23] = 23*22*C[21]*dC1_dr*dC1_dr + 23*C[22]*d2C1_dr2
        d2C_dr2[24] = 24*23*C[22]*dC1_dr*dC1_dr + 24*C[23]*d2C1_dr2
        d2C_dr2[25] = 25*24*C[23]*dC1_dr*dC1_dr + 25*C[24]*d2C1_dr2
        d2C_dr2[26] = 26*25*C[24]*dC1_dr*dC1_dr + 26*C[25]*d2C1_dr2
        dC_dtheta = _ovec(T, 27)
        dC_dtheta[0] = 0
        dC_dtheta[1] = 1*C[0]*dC1_dtheta
        dC_dtheta[2] = 2*C[1]*dC1_dtheta
        dC_dtheta[3] = 3*C[2]*dC1_dtheta
        dC_dtheta[4] = 4*C[3]*dC1_dtheta
        dC_dtheta[5] = 5*C[4]*dC1_dtheta
        dC_dtheta[6] = 6*C[5]*dC1_dtheta
        dC_dtheta[7] = 7*C[6]*dC1_dtheta
        dC_dtheta[8] = 8*C[7]*dC1_dtheta
        dC_dtheta[9] = 9*C[8]*dC1_dtheta
        dC_dtheta[10] = 10*C[9]*dC1_dtheta
        dC_dtheta[11] = 11*C[10]*dC1_dtheta
        dC_dtheta[12] = 12*C[11]*dC1_dtheta
        dC_dtheta[13] = 13*C[12]*dC1_dtheta
        dC_dtheta[14] = 14*C[13]*dC1_dtheta
        dC_dtheta[15] = 15*C[14]*dC1_dtheta
        dC_dtheta[16] = 16*C[15]*dC1_dtheta
        dC_dtheta[17] = 17*C[16]*dC1_dtheta
        dC_dtheta[18] = 18*C[17]*dC1_dtheta
        dC_dtheta[19] = 19*C[18]*dC1_dtheta
        dC_dtheta[20] = 20*C[19]*dC1_dtheta
        dC_dtheta[21] = 21*C[20]*dC1_dtheta
        dC_dtheta[22] = 22*C[21]*dC1_dtheta
        dC_dtheta[23] = 23*C[22]*dC1_dtheta
        dC_dtheta[24] = 24*C[23]*dC1_dtheta
        dC_dtheta[25] = 25*C[24]*dC1_dtheta
        dC_dtheta[26] = 26*C[25]*dC1_dtheta
        d2C_dtheta2 = _ovec(T, 27)
        d2C_dtheta2[0] = 0
        d2C_dtheta2[1] = d2C1_dtheta2
        d2C_dtheta2[2] = 2*1*C[0]*dC1_dtheta*dC1_dtheta + 2*C[1]*d2C1_dtheta2
        d2C_dtheta2[3] = 3*2*C[1]*dC1_dtheta*dC1_dtheta + 3*C[2]*d2C1_dtheta2
        d2C_dtheta2[4] = 4*3*C[2]*dC1_dtheta*dC1_dtheta + 4*C[3]*d2C1_dtheta2
        d2C_dtheta2[5] = 5*4*C[3]*dC1_dtheta*dC1_dtheta + 5*C[4]*d2C1_dtheta2
        d2C_dtheta2[6] = 6*5*C[4]*dC1_dtheta*dC1_dtheta + 6*C[5]*d2C1_dtheta2
        d2C_dtheta2[7] = 7*6*C[5]*dC1_dtheta*dC1_dtheta + 7*C[6]*d2C1_dtheta2
        d2C_dtheta2[8] = 8*7*C[6]*dC1_dtheta*dC1_dtheta + 8*C[7]*d2C1_dtheta2
        d2C_dtheta2[9] = 9*8*C[7]*dC1_dtheta*dC1_dtheta + 9*C[8]*d2C1_dtheta2
        d2C_dtheta2[10] = 10*9*C[8]*dC1_dtheta*dC1_dtheta + 10*C[9]*d2C1_dtheta2
        d2C_dtheta2[11] = 11*10*C[9]*dC1_dtheta*dC1_dtheta + 11*C[10]*d2C1_dtheta2
        d2C_dtheta2[12] = 12*11*C[10]*dC1_dtheta*dC1_dtheta + 12*C[11]*d2C1_dtheta2
        d2C_dtheta2[13] = 13*12*C[11]*dC1_dtheta*dC1_dtheta + 13*C[12]*d2C1_dtheta2
        d2C_dtheta2[14] = 14*13*C[12]*dC1_dtheta*dC1_dtheta + 14*C[13]*d2C1_dtheta2
        d2C_dtheta2[15] = 15*14*C[13]*dC1_dtheta*dC1_dtheta + 15*C[14]*d2C1_dtheta2
        d2C_dtheta2[16] = 16*15*C[14]*dC1_dtheta*dC1_dtheta + 16*C[15]*d2C1_dtheta2
        d2C_dtheta2[17] = 17*16*C[15]*dC1_dtheta*dC1_dtheta + 17*C[16]*d2C1_dtheta2
        d2C_dtheta2[18] = 18*17*C[16]*dC1_dtheta*dC1_dtheta + 18*C[17]*d2C1_dtheta2
        d2C_dtheta2[19] = 19*18*C[17]*dC1_dtheta*dC1_dtheta + 19*C[18]*d2C1_dtheta2
        d2C_dtheta2[20] = 20*19*C[18]*dC1_dtheta*dC1_dtheta + 20*C[19]*d2C1_dtheta2
        d2C_dtheta2[21] = 21*20*C[19]*dC1_dtheta*dC1_dtheta + 21*C[20]*d2C1_dtheta2
        d2C_dtheta2[22] = 22*21*C[20]*dC1_dtheta*dC1_dtheta + 22*C[21]*d2C1_dtheta2
        d2C_dtheta2[23] = 23*22*C[21]*dC1_dtheta*dC1_dtheta + 23*C[22]*d2C1_dtheta2
        d2C_dtheta2[24] = 24*23*C[22]*dC1_dtheta*dC1_dtheta + 24*C[23]*d2C1_dtheta2
        d2C_dtheta2[25] = 25*24*C[23]*dC1_dtheta*dC1_dtheta + 25*C[24]*d2C1_dtheta2
        d2C_dtheta2[26] = 26*25*C[24]*dC1_dtheta*dC1_dtheta + 26*C[25]*d2C1_dtheta2
        (ellK, ellE) = _ellKE_arg(C1)
        ellip = _ovec0(T[ellK, ellE])
        dellE_dC = (ellK - ellE)/(T(2.0)*(1+C1))
        dellK_dC = (C1*ellK - (1+C1)*ellE)/(T(2.0)*C1*(1+C1))
        d2ellE_dC2 = -(2*C1*ellK - (2*C1-1)*ellE)/(T(4.0)*C1*(1+C1)*(1+C1))
        d2ellK_dC2 = -(C1*(1+2*C1)*ellK - 2*(1+C1)*(1+C1)*ellE)/(T(4.0)*C1*C1*(1+C1)*(1+C1))
        dellE_dr = dellE_dC * dC1_dr
        dellE_dtheta = dellE_dC * dC1_dtheta
        d2ellE_dr2 = d2ellE_dC2 * dC1_dr * dC1_dr + dellE_dC * d2C1_dr2
        d2ellE_dtheta2 = d2ellE_dC2 * dC1_dtheta * dC1_dtheta + dellE_dC * d2C1_dtheta2
        dellK_dr = dellK_dC * dC1_dr
        dellK_dtheta = dellK_dC * dC1_dtheta
        d2ellK_dr2 = d2ellK_dC2 * dC1_dr * dC1_dr + dellK_dC * d2C1_dr2
        d2ellK_dtheta2 = d2ellK_dC2 * dC1_dtheta * dC1_dtheta + dellK_dC * d2C1_dtheta2
        dellip_dr = _ovec0(T[dellK_dr, dellE_dr])
        dellip_dtheta = _ovec0(T[dellK_dtheta, dellE_dtheta])
        d2ellip_dr2 = _ovec0(T[d2ellK_dr2, d2ellE_dr2])
        d2ellip_dtheta2 = _ovec0(T[d2ellK_dtheta2, d2ellE_dtheta2])
        if m>20
            error("effsource: requested m-mode is not supported (m>20)")
        end
        num = zero(T)
        num_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    num, num_c = _cadd(cm, num, num_c, reei(T,m,i,j,k)*ellip[i]*A[j]*C[k])
                end
            end
        end
        num = num + num_c
        dnum_dr = zero(T)
        dnum_dr_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    dnum_dr, dnum_dr_c = _cadd(cm, dnum_dr, dnum_dr_c, reei(T,m,i,j,k)*
            (dellip_dr[i]*A[j]*C[k]
           + ellip[i]*dA_dr[j]*C[k]
           + ellip[i]*A[j]*dC_dr[k]))
                end
            end
        end
        dnum_dr = dnum_dr + dnum_dr_c
        d2num_dr2 = zero(T)
        d2num_dr2_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    d2num_dr2, d2num_dr2_c = _cadd(cm, d2num_dr2, d2num_dr2_c, reei(T,m,i,j,k)*
            (d2ellip_dr2[i]*A[j]*C[k]
           + dellip_dr[i]*dA_dr[j]*C[k]
           + dellip_dr[i]*A[j]*dC_dr[k]
           + dellip_dr[i]*dA_dr[j]*C[k]
           + ellip[i]*d2A_dr2[j]*C[k]
           + ellip[i]*dA_dr[j]*dC_dr[k]
           + dellip_dr[i]*A[j]*dC_dr[k]
           + ellip[i]*dA_dr[j]*dC_dr[k]
           + ellip[i]*A[j]*d2C_dr2[k]))
                end
            end
        end
        d2num_dr2 = d2num_dr2 + d2num_dr2_c
        dnum_dtheta = zero(T)
        dnum_dtheta_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    dnum_dtheta, dnum_dtheta_c = _cadd(cm, dnum_dtheta, dnum_dtheta_c, reei(T,m,i,j,k)*
            (dellip_dtheta[i]*A[j]*C[k]
           + ellip[i]*dA_dtheta[j]*C[k]
           + ellip[i]*A[j]*dC_dtheta[k]))
                end
            end
        end
        dnum_dtheta = dnum_dtheta + dnum_dtheta_c
        d2num_dtheta2 = zero(T)
        d2num_dtheta2_c = zero(T)
        for i in 0:(2)-1
            for j in 0:(5)-1
                for k in 0:(27)-1
                    d2num_dtheta2, d2num_dtheta2_c = _cadd(cm, d2num_dtheta2, d2num_dtheta2_c, reei(T,m,i,j,k)*
            (d2ellip_dtheta2[i]*A[j]*C[k]
           + dellip_dtheta[i]*dA_dtheta[j]*C[k]
           + dellip_dtheta[i]*A[j]*dC_dtheta[k]
           + dellip_dtheta[i]*dA_dtheta[j]*C[k]
           + ellip[i]*d2A_dtheta2[j]*C[k]
           + ellip[i]*dA_dtheta[j]*dC_dtheta[k]
           + dellip_dtheta[i]*A[j]*dC_dtheta[k]
           + ellip[i]*dA_dtheta[j]*dC_dtheta[k]
           + ellip[i]*A[j]*d2C_dtheta2[k]))
                end
            end
        end
        d2num_dtheta2 = d2num_dtheta2 + d2num_dtheta2_c
        s = beta*C[3]*((alpha+beta)^(2) * sqrt(alpha+beta))
        ds_dr = beta*(3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dr + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dr)
        ds_dtheta = beta*(3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dtheta + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dtheta)
        d2s_dr2 = beta*(6*C1*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dr*dC1_dr
               + 3*C[2]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dr*dC1_dr
               + 3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*d2C1_dr2
               + 3*C[2]*dC1_dr*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dr
               + C[3]*T(2.5)*T(1.5)*((alpha+beta)^(0) * sqrt(alpha+beta))*dalpha_dr*dalpha_dr
               + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*d2alpha_dr2)
        d2s_dtheta2 = beta*(6*C1*((alpha+beta)^(2) * sqrt(alpha+beta))*dC1_dtheta*dC1_dtheta
               + 3*C[2]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dtheta*dC1_dtheta
               + 3*C[2]*((alpha+beta)^(2) * sqrt(alpha+beta))*d2C1_dtheta2
               + 3*C[2]*dC1_dtheta*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*dalpha_dtheta
               + C[3]*T(2.5)*T(1.5)*((alpha+beta)^(0) * sqrt(alpha+beta))*dalpha_dtheta*dalpha_dtheta
               + C[3]*T(2.5)*((alpha+beta)^(1) * sqrt(alpha+beta))*d2alpha_dtheta2)
        RePhiS = T(4.0)*num/s
        dPhiS_dt = - m * om * (RePhiS)
        dPhiS_dr = T(4.0)*(-ds_dr*num + dnum_dr*s) /(s*s)
        dPhiS_dth = T(4.0)*(-ds_dtheta*num + dnum_dtheta*s)/(s*s)
        dPhiS_dph = m * (RePhiS)
        d2PhiS_dr2 = T(4.0)*(T(2.0)*ds_dr*ds_dr*num - s*(2*dnum_dr*ds_dr + d2s_dr2*num) + d2num_dr2*s*s)/(s*s*s)
        d2PhiS_dth2 = T(4.0)*(T(2.0)*ds_dtheta*ds_dtheta*num - s*(2*dnum_dtheta*ds_dtheta + d2s_dtheta2*num) + d2num_dtheta2*s*s)/(s*s*s)
        d2PhiS_dph2 = - m*m*(RePhiS)
        d2PhiS_dt2 = - m*m*om*om*(RePhiS)
        d2PhiS_dtph = m*m*om*(RePhiS)
        d2PhiS_dtr = T(NaN)
        d2PhiS_dtth = T(NaN)
        d2PhiS_drth = T(NaN)
        d2PhiS_drph = T(NaN)
        d2PhiS_dthph = T(NaN)
        sinth = sin(theta)
        sinth2 = sinth*sinth
        sin2th = sin(2*theta)
        cos2th = cos(2*theta)
        r2 = r*r
        r3 = r2*r
        r4 = r2*r2
        a2 = a*a
        a4 = a2*a2
        effsrc = -(_csum(cm, 2*a2*dPhiS_dr, - a2*d2PhiS_dph2, - a4*d2PhiS_dr2, - a2*d2PhiS_dth2, - 4*dPhiS_dr*r, - 2*a2*dPhiS_dr*r, 4*d2PhiS_dph2*r, 2*a*d2PhiS_dtph*r, 4*a2*d2PhiS_dr2*r, 2*d2PhiS_dth2*r, 6*dPhiS_dr*r2, - 2*d2PhiS_dph2*r2, - 4*d2PhiS_dr2*r2, -
         2*a2*d2PhiS_dr2*r2, - d2PhiS_dth2*r2, - 2*dPhiS_dr*r3, 4*d2PhiS_dr2*r3, - d2PhiS_dr2*r4, (a4*d2PhiS_dt2 + 4*a*d2PhiS_dtph*r + 2*d2PhiS_dt2*r4 + a2*d2PhiS_dt2*r*(2 + 3*r))*sinth2, cos2th*(a4*d2PhiS_dr2 - 2*a*d2PhiS_dtph*r + (-2 + r)*r*(d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) + d2PhiS_dr2*(-2 + r)*r) +
            a2*(-d2PhiS_dph2 + d2PhiS_dth2 + 2*dPhiS_dr*(-1 + r) - 4*d2PhiS_dr2*r + 2*d2PhiS_dr2*r2) +
            a2*d2PhiS_dt2*(a2 + (-2 + r)*r)*sinth2), - a2*dPhiS_dth*sin2th, 2*dPhiS_dth*r*sin2th, -
         dPhiS_dth*r2*sin2th))/((sinth2*(a2 + (-2 + r)*r)*(a2 + 2*r2 + a2*cos2th)))
        cosmph = cos(m*xp.phi)
        sinmph = sin(m*xp.phi)
        PhiS[0] = RePhiS*cosmph
        PhiS[1] = - RePhiS*sinmph
        dPhiS_dx[0] = dPhiS_dt*sinmph
        dPhiS_dx[1] = dPhiS_dt*cosmph
        dPhiS_dx[2] = dPhiS_dr*cosmph
        dPhiS_dx[3] = - dPhiS_dr*sinmph
        dPhiS_dx[4] = dPhiS_dth*cosmph
        dPhiS_dx[5] = - dPhiS_dth*sinmph
        dPhiS_dx[6] = dPhiS_dph*sinmph
        dPhiS_dx[7] = dPhiS_dph*cosmph
        d2PhiS_dx2[0] = d2PhiS_dt2*cosmph
        d2PhiS_dx2[1] = - d2PhiS_dt2*sinmph
        d2PhiS_dx2[2] = d2PhiS_dtr*cosmph
        d2PhiS_dx2[3] = - d2PhiS_dtr*sinmph
        d2PhiS_dx2[4] = d2PhiS_dtth*cosmph
        d2PhiS_dx2[5] = - d2PhiS_dtth*sinmph
        d2PhiS_dx2[6] = d2PhiS_dtph*cosmph
        d2PhiS_dx2[7] = - d2PhiS_dtph*sinmph
        d2PhiS_dx2[8] = d2PhiS_dr2*cosmph
        d2PhiS_dx2[9] = - d2PhiS_dr2*sinmph
        d2PhiS_dx2[10] = d2PhiS_drth*cosmph
        d2PhiS_dx2[11] = - d2PhiS_drth*sinmph
        d2PhiS_dx2[12] = d2PhiS_drph*cosmph
        d2PhiS_dx2[13] = - d2PhiS_drph*sinmph
        d2PhiS_dx2[14] = d2PhiS_dth2*cosmph
        d2PhiS_dx2[15] = - d2PhiS_dth2*sinmph
        d2PhiS_dx2[16] = d2PhiS_dthph*cosmph
        d2PhiS_dx2[17] = - d2PhiS_dthph*sinmph
        d2PhiS_dx2[18] = d2PhiS_dph2*cosmph
        d2PhiS_dx2[19] = - d2PhiS_dph2*sinmph
        src[0] = effsrc*cosmph
        src[1] = - effsrc*sinmph
    return (Complex(PhiS[0], PhiS[1]),
            SVector{4,Complex{T}}(Complex(dPhiS_dx[0], dPhiS_dx[1]),
                                  Complex(dPhiS_dx[2], dPhiS_dx[3]),
                                  Complex(dPhiS_dx[4], dPhiS_dx[5]),
                                  Complex(dPhiS_dx[6], dPhiS_dx[7])),
            SVector{10,Complex{T}}(Complex(d2PhiS_dx2[0], d2PhiS_dx2[1]),
                                   Complex(d2PhiS_dx2[2], d2PhiS_dx2[3]),
                                   Complex(d2PhiS_dx2[4], d2PhiS_dx2[5]),
                                   Complex(d2PhiS_dx2[6], d2PhiS_dx2[7]),
                                   Complex(d2PhiS_dx2[8], d2PhiS_dx2[9]),
                                   Complex(d2PhiS_dx2[10], d2PhiS_dx2[11]),
                                   Complex(d2PhiS_dx2[12], d2PhiS_dx2[13]),
                                   Complex(d2PhiS_dx2[14], d2PhiS_dx2[15]),
                                   Complex(d2PhiS_dx2[16], d2PhiS_dx2[17]),
                                   Complex(d2PhiS_dx2[18], d2PhiS_dx2[19])),
            Complex(src[0], src[1]))
end

