# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _effsource_equatorial
else:
    import _effsource_equatorial

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class doubleArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _effsource_equatorial.doubleArray_swiginit(self, _effsource_equatorial.new_doubleArray(nelements))
    __swig_destroy__ = _effsource_equatorial.delete_doubleArray

    def __getitem__(self, index):
        return _effsource_equatorial.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _effsource_equatorial.doubleArray___setitem__(self, index, value)

    def cast(self):
        return _effsource_equatorial.doubleArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _effsource_equatorial.doubleArray_frompointer(t)

# Register doubleArray in _effsource_equatorial:
_effsource_equatorial.doubleArray_swigregister(doubleArray)
class coordinate(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r = property(_effsource_equatorial.coordinate_r_get, _effsource_equatorial.coordinate_r_set)
    theta = property(_effsource_equatorial.coordinate_theta_get, _effsource_equatorial.coordinate_theta_set)
    phi = property(_effsource_equatorial.coordinate_phi_get, _effsource_equatorial.coordinate_phi_set)
    t = property(_effsource_equatorial.coordinate_t_get, _effsource_equatorial.coordinate_t_set)

    def __init__(self):
        _effsource_equatorial.coordinate_swiginit(self, _effsource_equatorial.new_coordinate())
    __swig_destroy__ = _effsource_equatorial.delete_coordinate

# Register coordinate in _effsource_equatorial:
_effsource_equatorial.coordinate_swigregister(coordinate)

def effsource_init(M, a):
    return _effsource_equatorial.effsource_init(M, a)

def effsource_set_particle(x_p, e, l, ur_p):
    return _effsource_equatorial.effsource_set_particle(x_p, e, l, ur_p)

def effsource_PhiS(x, PhiS):
    return _effsource_equatorial.effsource_PhiS(x, PhiS)

def effsource_calc(x, PhiS, dPhiS_dx, d2PhiS_dx2, src):
    return _effsource_equatorial.effsource_calc(x, PhiS, dPhiS_dx, d2PhiS_dx2, src)

def effsource_PhiS_m(m, x, PhiS):
    return _effsource_equatorial.effsource_PhiS_m(m, x, PhiS)

def effsource_calc_m(m, x, PhiS, dPhiS_dx, d2PhiS_dx2, src):
    return _effsource_equatorial.effsource_calc_m(m, x, PhiS, dPhiS_dx, d2PhiS_dx2, src)

def disable_gsl_error_handler():
    return _effsource_equatorial.disable_gsl_error_handler()

def make_coordinate(t=0.0, r=0.0, theta=0.0, phi=0.0):
    """Create a coordinate struct with the given values."""
    x = coordinate()
    x.t = t
    x.r = r
    x.theta = theta
    x.phi = phi
    return x

def calc_PhiS(x):
    """Compute singular field at point x.

    Returns: float
    """
    buf = doubleArray(1)
    effsource_PhiS(x, buf.cast())
    return buf[0]

def calc_PhiS_m(m, x):
    """Compute m-mode of singular field at point x.

    Returns: (Re, Im) tuple
    """
    buf = doubleArray(2)
    effsource_PhiS_m(m, x, buf.cast())
    return buf[0], buf[1]

def calc(x):
    """Compute effective source at point x.

    Returns: (PhiS, dPhiS_dx, d2PhiS_dx2, src)
        PhiS: float - singular field
        dPhiS_dx: list[4] - first derivatives [t, r, theta, phi]
        d2PhiS_dx2: list[10] - second derivatives
        src: float - effective source
    """
    _PhiS = doubleArray(1)
    _dPhiS = doubleArray(4)
    _d2PhiS = doubleArray(10)
    _src = doubleArray(1)
    effsource_calc(x, _PhiS.cast(), _dPhiS.cast(), _d2PhiS.cast(), _src.cast())
    return (
        _PhiS[0],
        [_dPhiS[i] for i in range(4)],
        [_d2PhiS[i] for i in range(10)],
        _src[0],
    )

def calc_m(m, x):
    """Compute m-mode effective source at point x.

    Returns: (PhiS, dPhiS, d2PhiS, src)
        PhiS: list[2] - [Re, Im] singular field
        dPhiS: list[8] - first derivatives (Re/Im interleaved)
        d2PhiS: list[20] - second derivatives (Re/Im interleaved)
        src: list[2] - [Re, Im] effective source
    """
    _PhiS = doubleArray(2)
    _dPhiS = doubleArray(8)
    _d2PhiS = doubleArray(20)
    _src = doubleArray(2)
    effsource_calc_m(m, x, _PhiS.cast(), _dPhiS.cast(), _d2PhiS.cast(), _src.cast())
    return (
        [_PhiS[i] for i in range(2)],
        [_dPhiS[i] for i in range(8)],
        [_d2PhiS[i] for i in range(20)],
        [_src[i] for i in range(2)],
    )


