#!/usr/bin/env python3
"""Extract the ReEI[21][2][5][27] table from kerr-circular-ctx.c into a Julia
data file (src/reei_data.jl).

The C initializer is a nested brace list of doubles in row-major order (last
index k fastest). We pull every numeric literal between the `=` and the
terminating `;`, verify the count (21*2*5*27 = 5670), and emit a flat vector
plus a 0-based index helper. Keeping it flat sidesteps C-row-major vs
Julia-column-major reshape confusion.
"""
import re
import sys
from pathlib import Path

DIMS = (21, 2, 5, 27)
EXPECTED = DIMS[0] * DIMS[1] * DIMS[2] * DIMS[3]  # 5670

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
SRC_C = REPO / "kerr-circular-ctx.c"
OUT_JL = HERE.parent / "src" / "reei_data.jl"


def extract():
    text = SRC_C.read_text()

    # Isolate the ReEI declaration's initializer: from the first '=' after the
    # declaration up to the matching terminating ';'.
    decl = text.index("ReEI[21][2][5][27]")
    eq = text.index("=", decl)
    semi = text.index(";", eq)
    body = text[eq + 1 : semi]

    # Strip C comments (// ... and /* ... */) that may appear in the block.
    body = re.sub(r"/\*.*?\*/", " ", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", " ", body)

    # Braces become nothing; split the remaining on commas.
    body = body.replace("{", " ").replace("}", " ")
    tokens = [t.strip() for t in body.split(",")]
    nums = []
    for t in tokens:
        if t == "":
            continue
        nums.append(float(t))

    if len(nums) != EXPECTED:
        sys.exit(f"ERROR: parsed {len(nums)} numbers, expected {EXPECTED}")
    return nums


def emit(nums):
    lines = []
    lines.append("# Auto-generated by tools/extract_reei.py -- do not edit by hand.")
    lines.append("# ReEI[21][2][5][27] complete-elliptic-integral expansion coefficients,")
    lines.append("# flattened in C row-major order (last index k fastest).")
    lines.append("")
    lines.append(f"const REEI_DIMS = {DIMS}")
    lines.append("const REEI_FLAT = Float64[")
    # 8 numbers per line for readability; repr() gives full round-trip precision.
    for i in range(0, len(nums), 8):
        chunk = ", ".join(repr(x) for x in nums[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("]")
    lines.append("")
    lines.append("# 0-based indices matching the C code: ReEI[m][i][j][k].")
    lines.append("# Coefficients are returned in type T so they do not promote a")
    lines.append("# low-precision working type back up to Float64.")
    lines.append(
        "@inline reei(::Type{T}, m::Integer, i::Integer, j::Integer, k::Integer) where {T} ="
    )
    lines.append(
        "    T(@inbounds REEI_FLAT[((m * 2 + i) * 5 + j) * 27 + k + 1])"
    )
    lines.append("")
    OUT_JL.write_text("\n".join(lines))
    print(f"Wrote {OUT_JL} ({len(nums)} coefficients)")


if __name__ == "__main__":
    emit(extract())
