#!/usr/bin/env python3
"""Generate the EffsourceCtx struct and set_particle! from the coefficient body,
so the ~50 A-coefficient field names are never hand-typed."""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
BODY = (HERE.parent / "src" / "_set_particle_body.jl").read_text().splitlines()

# field names in assignment order (A#### coefficients + alpha20/alpha02/beta).
# Each body line is `    NAME = <expr>` (a local coefficient assignment).
coeffs = []
for line in BODY:
    m = re.match(r"\s*([A-Za-z_]\w*)\s*=", line)
    if m:
        coeffs.append(m.group(1))

fields = ["    " + f"{c}::T" for c in coeffs]
struct = """\
# Auto-generated by tools/generate_struct.py -- do not edit by hand.

\"\"\"Field point / particle location, matching C `struct coordinate`.\"\"\"
struct Coordinate{T}
    r::T
    theta::T
    phi::T
    t::T
end
Coordinate{T}(; r=zero(T), theta=zero(T), phi=zero(T), t=zero(T)) where {T} =
    Coordinate{T}(T(r), T(theta), T(phi), T(t))

\"\"\"Thread-safe effective-source context for circular Kerr orbits, generic over
the numeric type T (Float64, Float32, Float32sr, BigFloat, ...).\"\"\"
mutable struct EffsourceCtx{T}
    M::T
    a::T
    xp::Coordinate{T}
""" + "\n".join(fields) + """

    EffsourceCtx{T}() where {T} = new{T}()
end

Base.eltype(::EffsourceCtx{T}) where {T} = T

\"\"\"Allocate a context for black-hole mass M and spin a.\"\"\"
function effsource_create(M, a)
    T0 = promote_type(typeof(M), typeof(a))
    T = T0 <: Integer ? Float64 : T0   # float-ify integer inputs, keep SR types
    ctx = EffsourceCtx{T}()
    ctx.M = T(M)
    ctx.a = T(a)
    ctx.xp = Coordinate{T}()
    return ctx
end
"""
Path(HERE.parent / "src" / "_ctx_struct.jl").write_text(struct)

# set_particle! wrapper around the generated coefficient body. Coefficients are
# computed in the `setup` precision T (default = the context type Tc) and stored
# rounded to Tc. Passing e.g. setup=Double64/BigFloat tames the heavy internal
# cancellation of the A#### expressions, which are computed once per particle.
body = "\n".join(BODY)
store = "\n".join(f"    ctx.{c} = Tc({c})" for c in coeffs)
setp = """\
# Auto-generated by tools/generate_struct.py -- do not edit by hand.

\"\"\"Compute the series-expansion coefficients for a particle at `x_p` with
energy E and angular momentum L (ur is unused for circular orbits, kept for API
parity).

Keyword `setup::Type` selects the precision used to evaluate the (ill-conditioned)
coefficient expressions; results are rounded to the context type. Defaults to the
context type, reproducing the direct computation exactly. Use e.g.
`setup=Double64` or `setup=BigFloat` to reduce set-up cancellation.\"\"\"
function set_particle!(ctx::EffsourceCtx{Tc}, x_p::Coordinate{Tc}, E, L, ur=zero(Tc);
                       setup::Type{T}=Tc) where {Tc,T}
    ctx.xp = x_p
    M = T(ctx.M)
    a = T(ctx.a)
    r = T(x_p.r)
    E = T(E)
    L = T(L)
""" + body + """
""" + store + """
    return ctx
end
"""
Path(HERE.parent / "src" / "_set_particle.jl").write_text(setp)
print(f"Wrote _ctx_struct.jl ({len(coeffs)} coefficient fields) and _set_particle.jl")
